force-app/main/default/objects/HOMEtracker__Service_File__c/HOMEtracker__Service_File__c.object-meta.xml
<CustomObject>
    <description>Applications for assistance, home purchases, and other services provided</description>
    <label>Service File</label>
    <nameField>
        <label>Service File Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Services</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/HOMEtracker__Service_File__c/fields/Application_Workflow_Status__c.field-meta.xml
<CustomField>
    <fullName>Application_Workflow_Status__c</fullName>
    <description>Used to track staff&apos;s progress through the income certification process.</description>
    <inlineHelpText>Tracks the status of the certification process.</inlineHelpText>
    <label>Application Workflow Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Invited - Waiting to Submit</fullName>
            </value>
            <value>
                <fullName>Waiting for Rental Pre-Screen</fullName>
            </value>
            <value>
                <fullName>Failed Pre-Screen</fullName>
            </value>
            <value>
                <fullName>Pre-Screen Complete, Not Yet Referred</fullName>
            </value>
            <value>
                <fullName>Application Received - Waiting for Credit Results</fullName>
                <label>Application Received - Waiting for Credit / Developer</label>
            </value>
            <value>
                <fullName>Application Received - Missing Mortgage Pre-Approval</fullName>
            </value>
            <value>
                <fullName>Application Received - Backup Ready for Full Income Certification</fullName>
                <color>#FFCC66</color>
                <label>Application Received - Backup Ready for Full Income Certification</label>
            </value>
            <value>
                <fullName>Application Received - Ready for Full Income Certification</fullName>
                <color>#F3D904</color>
                <label>Application Received - Ready for Full Income Certification</label>
            </value>
            <value>
                <fullName>Application Received - Full Income Certification In Progress</fullName>
                <color>#3366FF</color>
                <label>Application Received - Full Income Certification In Progress</label>
            </value>
            <value>
                <fullName>Application Received - Ready for Peer Review</fullName>
                <color>#9999FF</color>
                <label>Application Received - Ready for Peer Review</label>
            </value>
            <value>
                <fullName>Application Received - Peer Review In Progress</fullName>
                <color>#CC33CC</color>
                <label>Application Received - Peer Review In Progress</label>
            </value>
            <value>
                <fullName>Application Received - Peer Review Completed</fullName>
                <color>#993399</color>
                <label>Application Received - Peer Review Completed</label>
            </value>
            <value>
                <fullName>Application Received - Peer Review Completed - On Hold</fullName>
                <color>#663366</color>
                <label>Application Received - Peer Review Completed - On Hold</label>
            </value>
            <value>
                <fullName>Application Received - Updating After Peer Review</fullName>
                <color>#339999</color>
                <label>Application Received - Updating After Peer Review</label>
            </value>
            <value>
                <fullName>Application Received - Certification Completed</fullName>
                <color>#78C953</color>
                <label>Application Received - Certification Completed</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/HOMEtracker__Service_File__c/fields/Cert_or_Inelig_Date__c.field-meta.xml
<CustomField>
    <fullName>Cert_or_Inelig_Date__c</fullName>
    <formula>IF( Certified__c = true,  Eligibility_Date__c ,
IF( Ineligibility__c = true,  Date_Application_Terminated_Withdrawn__c ,
null))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Cert or Inelig Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/HOMEtracker__Service_File__c/fields/Certified__c.field-meta.xml
<CustomField>
    <fullName>Certified__c</fullName>
    <formula>OR(
ISPICKVAL( HOMEtracker__Status__c , &quot;Certified - Pending Final Documents&quot;),
ISPICKVAL( HOMEtracker__Status__c ,&quot;Certified - Backup&quot;),
ISPICKVAL( HOMEtracker__Status__c ,&quot;Certified - Pending Closing&quot;),
ISPICKVAL( HOMEtracker__Status__c ,&quot;Certified - On Hold&quot;),
ISPICKVAL( HOMEtracker__Status__c ,&quot;Current Owner&quot;),
ISPICKVAL( HOMEtracker__Status__c ,&quot;Current Renter&quot;),
ISPICKVAL( HOMEtracker__Status__c ,&quot;Past Owner&quot;),
ISPICKVAL( HOMEtracker__Status__c ,&quot;Past Renter&quot;)
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Certified by status for reports.  Checked true for following statuses: Certified - Pending Final Documents,Certified - Pending Closing,Current Owner,Current Renter,Past Owner,Past Renter</inlineHelpText>
    <label>Certified</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/HOMEtracker__Service_File__c/fields/HOMEtracker__Applicant__c.field-meta.xml
<CustomField>
    <fullName>HOMEtracker__Applicant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Autofills from the Application Household Member record with the Application Role set to Primary Applicant.</description>
    <inlineHelpText>Autofills from the Application Household Member record with the Application Role set to Primary Applicant.</inlineHelpText>
    <label>Applicant</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Services (Applicant)</relationshipLabel>
    <relationshipName>R00N60000001ScFBEA0</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/HOMEtracker__Service_File__c/fields/Ineligibility__c.field-meta.xml
<CustomField>
    <fullName>Ineligibility__c</fullName>
    <formula>OR(
ISPICKVAL( HOMEtracker__Status__c , &quot;Failed Income Certification - Pending Appeal&quot;),
ISPICKVAL( HOMEtracker__Status__c , &quot;Failed Income Certification&quot;),
ISPICKVAL( HOMEtracker__Status__c , &quot;Withdrawn / No Longer Interested&quot;),
ISPICKVAL( HOMEtracker__Status__c , &quot;Certified - Expired&quot;)
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Ineligibility by Status for reports.  Check true if one of these statuses: Failed Income Certification - Pending Appeal,Failed Income Certification,Withdrawn - No Longer Interested,Certified - On Hold,Certified - Expired</inlineHelpText>
    <label>Ineligibility</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/HOMEtracker__Service_File__c/fields/PHA__Application_Status__c.field-meta.xml
<CustomField>
    <fullName>PHA__Application_Status__c</fullName>
    <inlineHelpText>Tracks the status of the Public House application.

Generally, auto updated by Public House. Applicants can only access Public House during the &quot;Invited&quot;, &quot;Incomplete&quot;, and &quot;Document Corrections&quot; statuses.</inlineHelpText>
    <label>Application Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Invited</fullName>
                <default>true</default>
                <label>Invited</label>
            </value>
            <value>
                <fullName>Incomplete</fullName>
            </value>
            <value>
                <fullName>Document Review</fullName>
            </value>
            <value>
                <fullName>Document Corrections</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
            <value>
                <fullName>Declined</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/HOMEtracker__Service_File__c/fields/PHA__Application_Submitted__c.field-meta.xml
<CustomField>
    <fullName>PHA__Application_Submitted__c</fullName>
    <label>Application Submitted</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/getApp.cls
public class getApp{

        public List<HOMEtracker__Service_File__c> getSF() {
        return [SELECT Name, PHA__Application_Submitted__c
                FROM
                HOMEtracker__Service_File__c
                WHERE
                PHA__Application_Status__c = 'Document Review' AND
                Application_Workflow_Status__c !='Application Received - Backup Ready for Full Income Certification' AND
                Application_Workflow_Status__c !='Application Received - Full Income Certification In Progress' AND
                Application_Workflow_Status__c !='Application Received - Ready for Peer Review' AND
                Application_Workflow_Status__c !='Application Received - Peer Review In Progress' AND
                Application_Workflow_Status__c !='Application Received - Peer Review Completed' AND
                (NOT HOMEtracker__Applicant__r.Name LIKE '%Test%')
                ORDER BY
                PHA__Application_Submitted__c ASC
                LIMIT 1];
        }
        
        public List<HOMEtracker__Service_File__c> getLWplus() {
        return [SELECT Name, PHA__Application_Submitted__c
                FROM
                HOMEtracker__Service_File__c
                WHERE
                PHA__Application_Status__c = 'Document Review' AND
                Application_Workflow_Status__c !='Application Received - Backup Ready for Full Income Certification' AND
                Application_Workflow_Status__c !='Application Received - Full Income Certification In Progress' AND
                Application_Workflow_Status__c !='Application Received - Ready for Peer Review' AND
                Application_Workflow_Status__c !='Application Received - Peer Review In Progress' AND
                Application_Workflow_Status__c !='Application Received - Peer Review Completed' AND
                (NOT HOMEtracker__Applicant__r.Name LIKE '%Test%')
                AND PHA__Application_Submitted__c = LAST_WEEK
                ORDER BY
                PHA__Application_Submitted__c ASC];
        }
        public List<HOMEtracker__Service_File__c> getLWminus() {
        return [SELECT Name, PHA__Application_Submitted__c
                FROM
                HOMEtracker__Service_File__c
                WHERE
                (Ineligibility__c = true OR
                Certified__c = true) AND
                (NOT HOMEtracker__Applicant__r.Name LIKE '%Test%')
                AND Cert_Or_Inelig_Date__c = LAST_WEEK
                ORDER BY
                Cert_Or_Inelig_Date__c ASC];
        }
        public List<HOMEtracker__Service_File__c> getBacklog() {
        return [SELECT Name, PHA__Application_Submitted__c
                FROM
                HOMEtracker__Service_File__c
                WHERE
                PHA__Application_Status__c = 'Document Review' AND
                Application_Workflow_Status__c !='Application Received - Backup Ready for Full Income Certification' AND
                Application_Workflow_Status__c !='Application Received - Full Income Certification In Progress' AND
                Application_Workflow_Status__c !='Application Received - Ready for Peer Review' AND
                Application_Workflow_Status__c !='Application Received - Peer Review In Progress' AND
                Application_Workflow_Status__c !='Application Received - Peer Review Completed' AND
                (NOT HOMEtracker__Applicant__r.Name LIKE '%Test%')
                ORDER BY
                PHA__Application_Submitted__c ASC];
        }
        
}