force-app/main/default/objects/HOMEtracker__Service_File__c/HOMEtracker__Service_File__c.object-meta.xml
<CustomObject>
    <description>Applications for assistance, home purchases, and other services provided</description>
    <label>Service File</label>
    <nameField>
        <label>Service File Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Services</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/HOMEtracker__Service_File__c/fields/Application_URL_Internal__c.field-meta.xml
<CustomField>
    <fullName>Application_URL_Internal__c</fullName>
    <formula>HOMEtracker__Applicant__r.PHA__ApplicationURLInternal__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Application URL (Internal)</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/HOMEtracker__Service_File__c/fields/Application_Workflow_Status__c.field-meta.xml
<CustomField>
    <fullName>Application_Workflow_Status__c</fullName>
    <description>Used to track staff&apos;s progress through the income certification process.</description>
    <inlineHelpText>Tracks the status of the certification process.</inlineHelpText>
    <label>Application Workflow Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Invited - Waiting to Submit</fullName>
            </value>
            <value>
                <fullName>Waiting for Rental Pre-Screen</fullName>
            </value>
            <value>
                <fullName>Failed Pre-Screen</fullName>
            </value>
            <value>
                <fullName>Pre-Screen Complete, Not Yet Referred</fullName>
            </value>
            <value>
                <fullName>Application Received - Waiting for Credit Results</fullName>
                <label>Application Received - Waiting for Credit / Developer</label>
            </value>
            <value>
                <fullName>Application Received - Missing Mortgage Pre-Approval</fullName>
            </value>
            <value>
                <fullName>Application Received - Backup Ready for Full Income Certification</fullName>
                <color>#FFCC66</color>
                <label>Application Received - Backup Ready for Full Income Certification</label>
            </value>
            <value>
                <fullName>Application Received - Ready for Full Income Certification</fullName>
                <color>#F3D904</color>
                <label>Application Received - Ready for Full Income Certification</label>
            </value>
            <value>
                <fullName>Application Received - Full Income Certification In Progress</fullName>
                <color>#3366FF</color>
                <label>Application Received - Full Income Certification In Progress</label>
            </value>
            <value>
                <fullName>Application Received - Ready for Peer Review</fullName>
                <color>#9999FF</color>
                <label>Application Received - Ready for Peer Review</label>
            </value>
            <value>
                <fullName>Application Received - Peer Review In Progress</fullName>
                <color>#CC33CC</color>
                <label>Application Received - Peer Review In Progress</label>
            </value>
            <value>
                <fullName>Application Received - Peer Review Completed</fullName>
                <color>#993399</color>
                <label>Application Received - Peer Review Completed</label>
            </value>
            <value>
                <fullName>Application Received - Peer Review Completed - On Hold</fullName>
                <color>#663366</color>
                <label>Application Received - Peer Review Completed - On Hold</label>
            </value>
            <value>
                <fullName>Application Received - Updating After Peer Review</fullName>
                <color>#339999</color>
                <label>Application Received - Updating After Peer Review</label>
            </value>
            <value>
                <fullName>Application Received - Certification Completed</fullName>
                <color>#78C953</color>
                <label>Application Received - Certification Completed</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/HOMEtracker__Service_File__c/fields/Cases_Check__c.field-meta.xml
<CustomField>
    <fullName>Cases_Check__c</fullName>
    <formula>HYPERLINK(
&quot;https://cgph.lightning.force.com/lightning/r/Report/00O6O000005tkpgUAA/view?queryScope=userFolders&amp;fv0=&quot;&amp;Id&amp;&quot;&amp;fv1=&quot;&amp; Pre_Applicant__r.Id &amp;&quot;&amp;fv2=&quot;&amp; HOMEtracker__Applicant__r.AccountId &amp; &quot;&amp;fv3=&quot;&amp; HOMEtracker__Applicant__r.Email ,
&quot;Cases Check&quot;,
&quot;_Blank&quot;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Cases Check</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/HOMEtracker__Service_File__c/fields/Date_Certification_Expires__c.field-meta.xml
<CustomField>
    <fullName>Date_Certification_Expires__c</fullName>
    <description>Auto calculated: &quot;Eligibility Date&quot; + 180</description>
    <formula>Eligibility_Date__c  + 180</formula>
    <inlineHelpText>Auto calculated: &quot;Eligibility Date&quot; + 180</inlineHelpText>
    <label>Date Certification Expires</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/HOMEtracker__Service_File__c/fields/Eligibility_Date__c.field-meta.xml
<CustomField>
    <fullName>Eligibility_Date__c</fullName>
    <inlineHelpText>The date the certificate of eligibility was issued.</inlineHelpText>
    <label>Eligibility Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/HOMEtracker__Service_File__c/fields/HOMEtracker__Status__c.field-meta.xml
<CustomField>
    <fullName>HOMEtracker__Status__c</fullName>
    <description>Please note: The data stored in this field is linked to the HomeKeeper National Data Hub. Please contact support if you want to add a new status. Select the current Status of this Service File. Tip: To update the status of the Service File, Property and Applicant Contact records at the same time, click the Update Status button.</description>
    <inlineHelpText>Tracks the status of the Service File. 

Tip: To update the status of the Service File, Property and Applicant Contact records at the same time, click the Update Status button.</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Pending Direct Application Invitation</fullName>
            </value>
            <value>
                <fullName>Application In Process - Alternate Property</fullName>
                <label>Application in Process - Alternate Property</label>
            </value>
            <value>
                <fullName>Application in Process - Docs Old</fullName>
            </value>
            <value>
                <fullName>Application in Process</fullName>
            </value>
            <value>
                <fullName>Failed Pre-Screen</fullName>
            </value>
            <value>
                <fullName>Failed Income Certification - Pending Appeal</fullName>
                <color>#FF0000</color>
                <label>Failed Income Certification - Pending Appeal</label>
            </value>
            <value>
                <fullName>Failed Income Certification</fullName>
                <color>#CC0000</color>
                <label>Failed Income Certification</label>
            </value>
            <value>
                <fullName>Withdrawn / No Longer Interested</fullName>
                <color>#CC33CC</color>
                <label>Withdrawn - No Longer Interested</label>
            </value>
            <value>
                <fullName>Withdrawn - Backup (Did Not Start Certification)</fullName>
                <label>Withdrawn - Did Not Start Certification (Backup, Duplicate, Switched Unit, No Supporting Docs)</label>
            </value>
            <value>
                <fullName>Withdrawn, Did Not Submit Application</fullName>
            </value>
            <value>
                <fullName>Certified - Pending Final Documents</fullName>
                <color>#FFCC33</color>
                <label>Certified - Pending Final Documents</label>
            </value>
            <value>
                <fullName>Certified - Pending Closing</fullName>
                <color>#33CC00</color>
                <label>Certified - Pending Closing</label>
            </value>
            <value>
                <fullName>Certified - Backup</fullName>
            </value>
            <value>
                <fullName>Certified - On Hold</fullName>
                <color>#6666CC</color>
                <label>Certified - On Hold</label>
            </value>
            <value>
                <fullName>Certified - Expired</fullName>
                <color>#6633FF</color>
                <label>Certified - Expired</label>
            </value>
            <value>
                <fullName>Current Owner</fullName>
                <color>#33CC00</color>
                <label>Current Owner</label>
            </value>
            <value>
                <fullName>Current Renter</fullName>
                <color>#FFCC33</color>
                <label>Current Renter</label>
            </value>
            <value>
                <fullName>Past Owner</fullName>
                <color>#33CC00</color>
                <label>Past Owner</label>
            </value>
            <value>
                <fullName>Past Renter</fullName>
                <color>#FFCC33</color>
                <label>Past Renter</label>
            </value>
            <value>
                <fullName>Application Complete</fullName>
            </value>
            <value>
                <fullName>Assistance Complete</fullName>
            </value>
            <value>
                <fullName>Ineligible</fullName>
            </value>
            <value>
                <fullName>Wait List</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Recertification - Certified</fullName>
            </value>
            <value>
                <fullName>Recertification - Ineligible</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/HOMEtracker__Service_File__c/fields/PHA__Application_Due_Date__c.field-meta.xml
<CustomField>
    <fullName>PHA__Application_Due_Date__c</fullName>
    <inlineHelpText>Date full application is due. Update this field if applicant has not submitted yet and you are extending the deadline.</inlineHelpText>
    <label>Application Due</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/HOMEtracker__Service_File__c/fields/PHA__Application_Status__c.field-meta.xml
<CustomField>
    <fullName>PHA__Application_Status__c</fullName>
    <inlineHelpText>Tracks the status of the Public House application.

Generally, auto updated by Public House. Applicants can only access Public House during the &quot;Invited&quot;, &quot;Incomplete&quot;, and &quot;Document Corrections&quot; statuses.</inlineHelpText>
    <label>Application Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Invited</fullName>
                <default>true</default>
                <label>Invited</label>
            </value>
            <value>
                <fullName>Incomplete</fullName>
            </value>
            <value>
                <fullName>Document Review</fullName>
            </value>
            <value>
                <fullName>Document Corrections</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
            <value>
                <fullName>Declined</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/HOMEtracker__Service_File__c/fields/PHA__Portal_Visits__c.field-meta.xml
<CustomField>
    <fullName>PHA__Portal_Visits__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Number of authenticated visits to the Public House Application Portal</description>
    <inlineHelpText>Number of authenticated visits to the Public House Application Portal</inlineHelpText>
    <label>Portal Visits</label>
    <precision>7</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/HOMEtracker__Service_File__c/fields/PHA__Total_Required_Documents__c.field-meta.xml
<CustomField>
    <fullName>PHA__Total_Required_Documents__c</fullName>
    <label>Total Required Documents</label>
    <summaryFilterItems>
        <field>PHA__Required_Document__c.PHA__Required__c</field>
        <operation>equals</operation>
        <value>True</value>
    </summaryFilterItems>
    <summaryForeignKey>PHA__Required_Document__c.PHA__Service_File__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/HOMEtracker__Service_File__c/fields/Pre_Applicant__c.field-meta.xml
<CustomField>
    <fullName>Pre_Applicant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Pre-Applicant</label>
    <referenceTo>PreApplicants__c</referenceTo>
    <relationshipLabel>Full Applications</relationshipLabel>
    <relationshipName>Services</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/HOMEtracker__Service_File__c/recordTypes/Rental.recordType-meta.xml
<RecordType>
    <fullName>Rental</fullName>
    <active>true</active>
    <label>Rental</label>
</RecordType>

force-app/main/default/classes/InviteStepOneExt.cls
public with sharing class InviteStepOneExt {
    public List<HOMEtracker__Service_File__c> ListSF {get; set;}
    public Application__c PreSub {get; set;}
    public String PreSubId {get; set;}
    public String PreAppId {get; set;}
    public String PreSubType {get; set;}

    public InviteStepOneExt(ApexPages.StandardController controller) {
    
    PreSub= (Application__c)controller.getRecord();
    PreSubId = PreSub.Id;
    PreSub = [select id, Pre_Applicant__r.Id, Property_Type__c from Application__c WHERE id = :PreSubId];
    PreAppId = PreSub.Pre_Applicant__r.Id;
    PreSubType = PreSub.Property_Type__c;
    String TypeNeeded = '';
    
        IF(PreSubType == 'Rental_Unit'){
            TypeNeeded = 'Rental';
        }
        IF(PreSubType == 'Homeownership'){
            TypeNeeded = 'Homeownership';
        }
   
    
    ListSF = [SELECT
                Id,
                Name,
                PHA__Application_Status__c,
                Application_Workflow_Status__c,
                HOMEtracker__Status__c,
                PHA__Application_Due_Date__c,
                Cases_Check__c,
                Application_URL_Internal__c,
                PHA__Portal_Visits__c,
                Date_Certification_Expires__c,
                PHA__Total_Required_Documents__c,
                RecordType.Name,
                Eligibility_Date__c
              FROM HOMEtracker__Service_File__c
              WHERE Pre_Applicant__r.Id = :PreAppId AND RecordType.Name = :TypeNeeded
              ORDER BY HOMEtracker__Status__c ASC];

    }

}