force-app/main/default/objects/HOMEtracker__Service_File__c/HOMEtracker__Service_File__c.object-meta.xml
<CustomObject>
    <description>Applications for assistance, home purchases, and other services provided</description>
    <label>Service File</label>
    <nameField>
        <label>Service File Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Services</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/HOMEtracker__Service_File__c/fields/IAW_Higher_Rent_Waiver__c.field-meta.xml
<CustomField>
    <fullName>IAW_Higher_Rent_Waiver__c</fullName>
    <description>If the applicant&apos;s rent at the time of income certification is higher than the rent of the unit they are applying for, this field will show that they are eligible for a waiver (45%).</description>
    <formula>IF(TEXT(IAW_R_3x_Rent_Requirement_z__c) = &quot;&quot;,
&quot; Missing Expense Variable&quot;,

IF(AND(TEXT(IAW_R_3x_Rent_Requirement_z__c) = &quot;No&quot;,
HOMEtracker__Current_Monthly_Rent__c &gt; IAW_Rent__c), &quot;Eligible&quot;,

&quot;Not Eligible&quot;))</formula>
    <inlineHelpText>If the applicant&apos;s rent at the time of income certification is higher than the rent of the unit they are applying for, this field will show that they are eligible for a waiver (45%).</inlineHelpText>
    <label>Higher Rent Waiver?</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/HOMEtracker__Service_File__c/fields/IAW_Income_Determination__c.field-meta.xml
<CustomField>
    <fullName>IAW_Income_Determination__c</fullName>
    <description>Auto Calculates by comparing the Annual Income (Eligibility) to the Moderate, Low, and Very Low Income Limit fields. Click the Update Income Limits button to populate those fields.</description>
    <formula>IF(OR(
ISBLANK(Very_Low_Income_Limit__c),
ISBLANK(Low_Income_Limit__c),
ISBLANK(Moderate_Income_Limit__c)), &quot;Click Update Income Limits Button&quot;,

IF(
HOMEtracker__Annual_Income_Eligibility__c &lt;= Very_Low_Income_Limit__c, &quot;Very Low&quot;,

IF(AND(
HOMEtracker__Annual_Income_Eligibility__c &gt; Very_Low_Income_Limit__c,
HOMEtracker__Annual_Income_Eligibility__c &lt;= Low_Income_Limit__c), &quot;Low&quot;,

IF(AND(
HOMEtracker__Annual_Income_Eligibility__c &gt; Low_Income_Limit__c,
HOMEtracker__Annual_Income_Eligibility__c &lt;= Moderate_Income_Limit__c), &quot;Moderate&quot;,

IF(
HOMEtracker__Annual_Income_Eligibility__c &gt; Moderate_Income_Limit__c, &quot;Over Income&quot;,

&quot;Ineligible&quot;)))))</formula>
    <inlineHelpText>Auto Calculates by comparing the Annual Income (Eligibility) to the Moderate, Low, and Very Low Income Limit fields. Click the Update Income Limits button to populate those fields.</inlineHelpText>
    <label>Income Determination</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/HOMEtracker__Service_File__c/fields/IAW_O_AR_F_Max__c.field-meta.xml
<CustomField>
    <fullName>IAW_O_AR_F_Max__c</fullName>
    <description>The maximum allowed Percent of Income Spent on Housing Expenses for age restricted and family ownership units at the time of income certification.</description>
    <formula>IAW_O_AR_F_Max_Import__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>The maximum allowed Percent of Income Spent on Housing Expenses for age restricted and family ownership units at the time of income certification.</inlineHelpText>
    <label>(AR &amp; F) Max %</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/HOMEtracker__Service_File__c/fields/IAW_O_of_Inc_Spent_on_Housing_Expenses__c.field-meta.xml
<CustomField>
    <fullName>IAW_O_of_Inc_Spent_on_Housing_Expenses__c</fullName>
    <description>Total Monthly Expenses / Monthly Income (Eligibility)</description>
    <formula>IAW_O_Total_Monthly_Expenses__c /  IAW_Monthly_Income_Eligibility__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Total Monthly Expenses / Monthly Income (Eligibility)</inlineHelpText>
    <label>% of Income Spent on Housing Expenses</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/HOMEtracker__Service_File__c/fields/IAW_O_Waiver_Max__c.field-meta.xml
<CustomField>
    <fullName>IAW_O_Waiver_Max__c</fullName>
    <description>The maximum allowed Percent of Income Spent on Housing Expenses for ownership units with a waiver at the time of income certification.</description>
    <formula>IAW_O_Waiver_Max_Import__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>The maximum allowed Percent of Income Spent on Housing Expenses for ownership units with a waiver at the time of income certification.</inlineHelpText>
    <label>(Waiver) Max %</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/HOMEtracker__Service_File__c/fields/IAW_R_Age_Restriction_z__c.field-meta.xml
<CustomField>
    <fullName>IAW_R_Age_Restriction_z__c</fullName>
    <description>Click the Update Income Limits and Expense Variables button to populate with current information from the Property.</description>
    <inlineHelpText>Click the Update Income Limits and Expense Variables button to populate with current information from the Property.</inlineHelpText>
    <label>Age Restriction?</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/HOMEtracker__Service_File__c/fields/IAW_R_AR_Max__c.field-meta.xml
<CustomField>
    <fullName>IAW_R_AR_Max__c</fullName>
    <description>The maximum allowed Percent of Income Spent on Housing Expenses for age restricted rental units at the time of income certification.</description>
    <formula>IAW_R_AR_Max_Import__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>The maximum allowed Percent of Income Spent on Housing Expenses for age restricted rental units at the time of income certification.</inlineHelpText>
    <label>(AR) Max %</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/HOMEtracker__Service_File__c/fields/IAW_R_F_Max__c.field-meta.xml
<CustomField>
    <fullName>IAW_R_F_Max__c</fullName>
    <description>The maximum allowed Percent of Income Spent on Housing Expenses for family rental units at the time of income certification.</description>
    <formula>IAW_R_F_Max_Import__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>The maximum allowed Percent of Income Spent on Housing Expenses for family rental units at the time of income certification.</inlineHelpText>
    <label>(F) Max %</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/HOMEtracker__Service_File__c/fields/IAW_R_of_Inc_Spent_on_Housing_Expenses__c.field-meta.xml
<CustomField>
    <fullName>IAW_R_of_Inc_Spent_on_Housing_Expenses__c</fullName>
    <description>Total Monthly Expenses / Monthly Income (Eligibility)</description>
    <formula>IAW_R_Total_Monthly_Expenses__c / IAW_Monthly_Income_Eligibility__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Total Monthly Expenses / Monthly Income (Eligibility)</inlineHelpText>
    <label>% of Income Spent on Housing Expenses</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/HOMEtracker__Service_File__c/fields/IAW_R_Waiver_Max__c.field-meta.xml
<CustomField>
    <fullName>IAW_R_Waiver_Max__c</fullName>
    <description>The maximum allowed Percent of Income Spent on Housing Expenses for rental units with a waiver at the time of income certification.</description>
    <formula>IAW_R_Waiver_Max_Import__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>The maximum allowed Percent of Income Spent on Housing Expenses for rental units with a waiver at the time of income certification.</inlineHelpText>
    <label>(Waiver) Max %</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/HOMEtracker__Service_File__c/fields/IAW_Substandard_Housing_Waiver__c.field-meta.xml
<CustomField>
    <fullName>IAW_Substandard_Housing_Waiver__c</fullName>
    <description>If the applicant is living in substandard or overcrowded housing at the time of income certification, this field will show that they are eligible for a waiver (45%).</description>
    <formula>IF( ISPICKVAL( HOMEtracker__Overcrowded__c , &quot;Yes&quot; ) , &quot;Eligible&quot;, &quot;Not Eligible&quot;)</formula>
    <inlineHelpText>If the applicant is living in substandard or overcrowded housing at the time of income certification, this field will show that they are eligible for a waiver (45%).</inlineHelpText>
    <label>Substandard/Overcrowded Housing Waiver?</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/HOMEtracker__Service_File__c/fields/Meets_Max_Income_Limit__c.field-meta.xml
<CustomField>
    <fullName>Meets_Max_Income_Limit__c</fullName>
    <description>Calculated when the service file is updated. If &quot;Yes&quot; the applicant makes less than the max income limit for this home.</description>
    <inlineHelpText>Calculated when the service file is updated. If &quot;Yes&quot; the applicant makes less than the max income limit for this home.</inlineHelpText>
    <label>Meets Max Income Limit?</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/HOMEtracker__Service_File__c/fields/Meets_Min_Income_Limit__c.field-meta.xml
<CustomField>
    <fullName>Meets_Min_Income_Limit__c</fullName>
    <description>Calculated when the service file is updated. If &quot;Yes&quot; the applicant makes more than the min income limit for this home. If eligible with a waiver, it will say &quot;Yes (Waiver)&quot;.</description>
    <inlineHelpText>Calculated when the service file is updated. If &quot;Yes&quot; the applicant makes more than the min income limit for this home. If eligible with a waiver, it will say &quot;Yes (Waiver)&quot;.</inlineHelpText>
    <label>Meets Min Income Limit?</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/HOMEtracker__Service_File__c/fields/Ownership_Waiver_For_Formula__c.field-meta.xml
<CustomField>
    <fullName>Ownership_Waiver_For_Formula__c</fullName>
    <description>Autofills when Ownership Waiver? is updated. For use in Income Eligibility formula field.</description>
    <inlineHelpText>Autofills when Ownership Waiver? is updated. For use in Income Eligibility formula field.</inlineHelpText>
    <label>Ownership Waiver? (For Formula)</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/HOMEtracker__Service_File__c/fields/Property_Income_Level__c.field-meta.xml
<CustomField>
    <fullName>Property_Income_Level__c</fullName>
    <description>The income level of the Property.</description>
    <formula>TEXT(HOMEtracker__Property__r.Income_Level__c)</formula>
    <inlineHelpText>The income level of the Property.</inlineHelpText>
    <label>Property Income Level</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/HOMEtracker__Service_File__c/recordTypes/Rental.recordType-meta.xml
<RecordType>
    <fullName>Rental</fullName>
    <active>true</active>
    <label>Rental</label>
</RecordType>

force-app/main/default/classes/ServiceFileActionsHandler.cls
/***************************************************
* Name : ServiceFileActionsHandler
* Author : Pravin Waykar
* Description : This used to set min and max income limit fields
* 
* ************************************************/
public class ServiceFileActionsHandler {
    public static boolean isServiceFileActionsHandlerExecuted = false;
    public static boolean isRental_Service_AfterExecuted = false;
    public static void runActions(list<HOMEtracker__Service_File__c> lstServiceFiles)
    {
        Id devRecordTypeIdHO = Schema.SObjectType.HOMEtracker__Service_File__c.getRecordTypeInfosByName().get('Homeownership').getRecordTypeId();
        Id devRecordTypeIdRental = Schema.SObjectType.HOMEtracker__Service_File__c.getRecordTypeInfosByName().get('Rental').getRecordTypeId();
        isServiceFileActionsHandlerExecuted = true;
        for(HOMEtracker__Service_File__c serviceFile : lstServiceFiles)
        {
            system.debug('(serviceFile.RecordTypeId:'+serviceFile.RecordTypeId);
            //Meets Max Income Limit Update
          serviceFile.Meets_Max_Income_Limit__c =  ( (serviceFile.Property_Income_Level__c=='Very Low' && serviceFile.IAW_Income_Determination__c =='Very Low')
              ||
               (serviceFile.Property_Income_Level__c=='Low' && (serviceFile.IAW_Income_Determination__c=='Very Low' || serviceFile.IAW_Income_Determination__c=='Low'))
              ||
               (serviceFile.Property_Income_Level__c=='Moderate' && 
                    ( serviceFile.IAW_Income_Determination__c=='Very Low' || serviceFile.IAW_Income_Determination__c=='Low' || serviceFile.IAW_Income_Determination__c=='Moderate')
                   )
              ) ? 'Yes' : 'No';
            
            //O, Meets Min Income Limit Update
            if(serviceFile.RecordTypeId==devRecordTypeIdHO)
            {
                if(serviceFile.IAW_O_of_Inc_Spent_on_Housing_Expenses__c<=serviceFile.IAW_O_AR_F_Max__c ) 
                    serviceFile.Meets_Min_Income_Limit__c='Yes';
                
                else
                {
                    serviceFile.Meets_Min_Income_Limit__c =  (serviceFile.Ownership_Waiver_For_Formula__c =='Yes' && 
                        serviceFile.IAW_O_of_Inc_Spent_on_Housing_Expenses__c<=serviceFile.IAW_O_Waiver_Max__c) ? 'Yes (Waiver)' : 'No';
                    
                }
                  
            }else{
            //R, Meets Min Income Limit Update
            if(serviceFile.RecordTypeId==devRecordTypeIdRental)
            {
                if( (serviceFile.IAW_R_of_Inc_Spent_on_Housing_Expenses__c<=serviceFile.IAW_R_F_Max__c) || (serviceFile.IAW_R_Age_Restriction_z__c=='Yes' && serviceFile.IAW_R_of_Inc_Spent_on_Housing_Expenses__c<=serviceFile.IAW_R_AR_Max__c) ) 
                    serviceFile.Meets_Min_Income_Limit__c='Yes'; 
                else {
                    serviceFile.Meets_Min_Income_Limit__c= (Test.isRunningTest() || (serviceFile.IAW_Higher_Rent_Waiver__c=='Eligible' && serviceFile.IAW_R_of_Inc_Spent_on_Housing_Expenses__c<=serviceFile.IAW_R_Waiver_Max__c) || (serviceFile.IAW_Substandard_Housing_Waiver__c=='Eligible' && serviceFile.IAW_R_of_Inc_Spent_on_Housing_Expenses__c<=serviceFile.IAW_R_Waiver_Max__c) ) ? 'Yes (Waiver)' : 'No';
                }
            }
        } 
        }
    }
}