force-app/main/default/objects/HOMEtracker__Property__c/HOMEtracker__Property__c.object-meta.xml
<CustomObject>
    <label>Property</label>
    <nameField>
        <label>Property Address</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Properties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/HOMEtracker__Property__c/fields/Active_Property__c.field-meta.xml
<CustomField>
    <fullName>Active_Property__c</fullName>
    <formula>ISBLANK(Development_address__c)=false &amp;&amp;
(RecordType.Name = &apos;Homeownership&apos; || RecordType.Name = &apos;Rental Unit&apos; )&amp;&amp;
Exclude_From_Inventory__c = false &amp;&amp;
CONTAINS(TEXT(HOMEtracker__Status__c),&apos;Available&apos;)&amp;&amp;
TEXT(Development_address__r.Google_Tracker_Review__c) != &apos;&apos;&amp;&amp;
TEXT(Development_address__r.Google_Tracker_Review__c) != &apos;No Review&apos;&amp;&amp;
Test_Property__c = false</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Active Property</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/HOMEtracker__Property__c/fields/Current_Outreach_Timeline__c.field-meta.xml
<CustomField>
    <fullName>Current_Outreach_Timeline__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Current Outreach Timeline</label>
    <referenceTo>Outreach_Timeline__c</referenceTo>
    <relationshipLabel>Properties</relationshipLabel>
    <relationshipName>Properties</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/HOMEtracker__Property__c/fields/Development_address__c.field-meta.xml
<CustomField>
    <fullName>Development_address__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Development Address</label>
    <referenceTo>HOMEtracker__Property__c</referenceTo>
    <relationshipLabel>Units</relationshipLabel>
    <relationshipName>Properties</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/HOMEtracker__Property__c/fields/Group_Property__c.field-meta.xml
<CustomField>
    <fullName>Group_Property__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Check this field if this property is being used to outreach for a group of similar properties in the same development.</description>
    <inlineHelpText>Check this field if this property is being used to outreach for a group of similar properties in the same development.</inlineHelpText>
    <label>Group Property?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/HOMEtracker__Property__c/fields/Group_Property_Parent__c.field-meta.xml
<CustomField>
    <fullName>Group_Property_Parent__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>If this property is a single unit that is part of a group property for outreach, enter the group property that it is a part of in this field.</inlineHelpText>
    <label>Group Property</label>
    <referenceTo>HOMEtracker__Property__c</referenceTo>
    <relationshipLabel>Properties (Group Property)</relationshipLabel>
    <relationshipName>Group_Properties</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/HOMEtracker__Property__c/fields/Include_on_Tracker__c.field-meta.xml
<CustomField>
    <fullName>Include_on_Tracker__c</fullName>
    <defaultValue>true</defaultValue>
    <inlineHelpText>Include this property on the tracker sent to developer / landlord / owner.</inlineHelpText>
    <label>Include on Tracker</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/HOMEtracker__Property__c/fields/Outreach_Applicant_Strategy__c.field-meta.xml
<CustomField>
    <fullName>Outreach_Applicant_Strategy__c</fullName>
    <inlineHelpText>The strategy selected will set the standard for how many applicants are needed for each available unit in this development.</inlineHelpText>
    <label>Outreach Applicant Strategy</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Standard</fullName>
                <default>true</default>
                <label>Standard</label>
            </value>
            <value>
                <fullName>Aggressive</fullName>
            </value>
            <value>
                <fullName>Minimal</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/HOMEtracker__Property__c/fields/Primary_Case_manager__c.field-meta.xml
<CustomField>
    <fullName>Primary_Case_manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Primary Case Manager</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.RecordType.Name</field>
            <operation>equals</operation>
            <value>Professional</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Properties (Primary Case manager)</relationshipLabel>
    <relationshipName>Properties2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/HOMEtracker__Property__c/fields/Primary_Outreach_Coordintor__c.field-meta.xml
<CustomField>
    <fullName>Primary_Outreach_Coordintor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Coordinator who is handling outreach for resale/rerental of home</inlineHelpText>
    <label>Primary Outreach Coordinator</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.RecordType.Name</field>
            <operation>equals</operation>
            <value>Professional</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Properties (Primary Outreach Coordintaor)</relationshipLabel>
    <relationshipName>Properties5</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/HOMEtracker__Service_File__c/HOMEtracker__Service_File__c.object-meta.xml
<CustomObject>
    <description>Applications for assistance, home purchases, and other services provided</description>
    <label>Service File</label>
    <nameField>
        <label>Service File Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Services</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/HOMEtracker__Service_File__c/fields/Application_Workflow_Status__c.field-meta.xml
<CustomField>
    <fullName>Application_Workflow_Status__c</fullName>
    <description>Used to track staff&apos;s progress through the income certification process.</description>
    <inlineHelpText>Tracks the status of the certification process.</inlineHelpText>
    <label>Application Workflow Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Invited - Waiting to Submit</fullName>
            </value>
            <value>
                <fullName>Waiting for Rental Pre-Screen</fullName>
            </value>
            <value>
                <fullName>Failed Pre-Screen</fullName>
            </value>
            <value>
                <fullName>Pre-Screen Complete, Not Yet Referred</fullName>
            </value>
            <value>
                <fullName>Application Received - Waiting for Credit Results</fullName>
                <label>Application Received - Waiting for Credit / Developer</label>
            </value>
            <value>
                <fullName>Application Received - Missing Mortgage Pre-Approval</fullName>
            </value>
            <value>
                <fullName>Application Received - Backup Ready for Full Income Certification</fullName>
                <color>#FFCC66</color>
                <label>Application Received - Backup Ready for Full Income Certification</label>
            </value>
            <value>
                <fullName>Application Received - Ready for Full Income Certification</fullName>
                <color>#F3D904</color>
                <label>Application Received - Ready for Full Income Certification</label>
            </value>
            <value>
                <fullName>Application Received - Full Income Certification In Progress</fullName>
                <color>#3366FF</color>
                <label>Application Received - Full Income Certification In Progress</label>
            </value>
            <value>
                <fullName>Application Received - Ready for Peer Review</fullName>
                <color>#9999FF</color>
                <label>Application Received - Ready for Peer Review</label>
            </value>
            <value>
                <fullName>Application Received - Peer Review In Progress</fullName>
                <color>#CC33CC</color>
                <label>Application Received - Peer Review In Progress</label>
            </value>
            <value>
                <fullName>Application Received - Peer Review Completed</fullName>
                <color>#993399</color>
                <label>Application Received - Peer Review Completed</label>
            </value>
            <value>
                <fullName>Application Received - Peer Review Completed - On Hold</fullName>
                <color>#663366</color>
                <label>Application Received - Peer Review Completed - On Hold</label>
            </value>
            <value>
                <fullName>Application Received - Updating After Peer Review</fullName>
                <color>#339999</color>
                <label>Application Received - Updating After Peer Review</label>
            </value>
            <value>
                <fullName>Application Received - Certification Completed</fullName>
                <color>#78C953</color>
                <label>Application Received - Certification Completed</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/HOMEtracker__Service_File__c/fields/HOMEtracker__Property__c.field-meta.xml
<CustomField>
    <fullName>HOMEtracker__Property__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup the property associated with this Service File. Tip: Create a Property record first before looking it up here. Please note: The data stored in this field is linked to the HomeKeeper National Data Hub. Do not change this field or hide it from the layout.</description>
    <inlineHelpText>Lookup the property associated with this Service File.

Tip: Create a Property record first before looking it up here.</inlineHelpText>
    <label>Property</label>
    <referenceTo>HOMEtracker__Property__c</referenceTo>
    <relationshipLabel>Services</relationshipLabel>
    <relationshipName>Property_Interests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/HOMEtracker__Service_File__c/fields/Include_on_Tracker__c.field-meta.xml
<CustomField>
    <fullName>Include_on_Tracker__c</fullName>
    <formula>AND(
OR(
AND(CONTAINS(TEXT(Application_Workflow_Status__c ),&apos;Application Received&apos;),NOT(Contains(TEXT(Application_Workflow_Status__c ),&apos;Backup&apos;))),
OR(
TEXT( HOMEtracker__Status__c )= &apos;Application in Process&apos;,
TEXT( HOMEtracker__Status__c )= &apos;Application in Process - Alternate Property&apos;,
TEXT( HOMEtracker__Status__c )= &apos;Application in Process - Old Docs&apos;
)
),
AND(
NOT(TEXT( HOMEtracker__Status__c )=&apos;Current Owner&apos;),
NOT(TEXT( HOMEtracker__Status__c )=&apos;Current Renter&apos;),
NOT(TEXT( HOMEtracker__Status__c )=&apos;Failed Income Certification&apos;),
NOT(TEXT( HOMEtracker__Status__c )=&apos;Failed Pre-Screen&apos;),
NOT(TEXT( HOMEtracker__Status__c )=&apos;Past Renter&apos;),
NOT(TEXT( HOMEtracker__Status__c )=&apos;&apos;),
NOT(CONTAINS(TEXT( HOMEtracker__Status__c ),&apos;Withdrawn&apos;))
)
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Include on Tracker</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/HOMEtracker__Service_File__c/fields/Outreach_Tracking__c.field-meta.xml
<CustomField>
    <fullName>Outreach_Tracking__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Outreach Tracking</label>
    <referenceTo>Outreach_Tracking__c</referenceTo>
    <relationshipLabel>Services</relationshipLabel>
    <relationshipName>Services</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Outreach_Tracking__c/Outreach_Tracking__c.object-meta.xml
<CustomObject>
    <description>Tracking fields for outreach</description>
    <label>Outreach Tracking</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Outreach Tracking</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Outreach_Tracking__c/fields/Include_on_Tracker__c.field-meta.xml
<CustomField>
    <fullName>Include_on_Tracker__c</fullName>
    <formula>AND(
Service_File__r.HOMEtracker__Property__r.Include_on_Tracker__c=true,
OR(
TEXT(Tracker_Status__c) =&apos;Primary&apos;,
TEXT(Tracker_Status__c)=&apos;Backup&apos;,
TEXT(Tracker_Status__c)=&apos;Flagged&apos;,
TEXT(Tracker_Status__c)=&apos;Hidden&apos;,
AND(TEXT(Tracker_Status__c)=&apos;Removed&apos;, Move_to_Removed_Report__c = false)),
Priority_Calc__c != 1000,
NOT(TEXT( Service_File__r.HOMEtracker__Status__c )=&apos;Current Owner&apos;),
NOT(TEXT( Service_File__r.HOMEtracker__Status__c )=&apos;Current Renter&apos;),
NOT(TEXT( Service_File__r.HOMEtracker__Status__c )=&apos;Past Renter&apos;),
NOT(TEXT( Service_File__r.HOMEtracker__Status__c )=&apos;&apos;),
NOT(CONTAINS(TEXT( Service_File__r.HOMEtracker__Status__c ),&apos;Withdrawn&apos;))
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Calculated from Service File Status Fields.</inlineHelpText>
    <label>Available for Tracker</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Outreach_Tracking__c/fields/Service_File__c.field-meta.xml
<CustomField>
    <fullName>Service_File__c</fullName>
    <label>Service File</label>
    <referenceTo>HOMEtracker__Service_File__c</referenceTo>
    <relationshipLabel>Outreach Tracking</relationshipLabel>
    <relationshipName>Outreach_Tracking</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/OutreachListAAcont.cls
public class OutreachListAAcont {
    Public List<HOMETracker__Property__c> propList {get; set;}
    Public String result {get; set;}
    public Map<Integer,List<String>> mapProps {get; set;}
    
    
    public OutreachListAAcont(){
        //initialize variables
        Integer mapKeyInt = 0;
        mapProps = new Map<Integer,List<String>>();
        Integer appListTotalSize = 0;
        Integer appListInvSize = 0;
        Integer appListSubSize= 0;
        String propId = '';
        String propType = '';
        String appsAllIDs = '';
        String appsInvIDs = '';
        String appsSubIDs = '';
        String groupCheck = '';
        Integer unitCount = 0;
        String result = '';

        //ALL APPLICANTS
        //get list of all curent applicants associated with properties 
            List<Outreach_Tracking__c> appsListTotal = [
                SELECT id, Service_File__r.HOMEtracker__Property__r.id
                FROM Outreach_Tracking__c
                WHERE Include_On_Tracker__c = true
                ORDER BY Service_File__r.Id ASC
                ];
        //ALL APPLICANTS
        //add ids of all current applicants to string
        for(Outreach_Tracking__c a : appsListTotal ){
           appsAllIDs = appsAllIDs + a.Service_File__r.HOMEtracker__Property__r.id + ', ';
           }
        
        // APPLICANTS INVITED TO SUBMIT
        List<Outreach_Tracking__c> appsListInv = [
                SELECT id, Service_File__r.HOMEtracker__Property__r.id
                FROM Outreach_Tracking__c
                WHERE Include_On_Tracker__c = true AND
                    Service_File__r.Application_Workflow_Status__c = 'Invited - Waiting to Submit'
                ORDER BY Service_File__r.Id ASC
                ];
        // APPLICANTS INVITED TO SUBMIT
        //add ids of all current applicants to string
        for(Outreach_Tracking__c b : appsListInv ){
           appsInvIDs = appsInvIDs + b.Service_File__r.HOMEtracker__Property__r.id + ', ';
           }
        
        //GET ALL PROPERTIES
        propList = [
            SELECT
                Id,
                Name,
                Development_Address__r.Name,
                Development_Address__r.Id,
                Development_Address__r.Primary_Case_manager__r.name,
                RecordType.Name,
                Group_Property__c,
                Group_Property_Parent__c,
                Group_Property_Parent__r.Id,
                Current_Outreach_Timeline__r.Next_Step__c,
                Development_Address__r.Outreach_Applicant_Strategy__c,
                Primary_Outreach_Coordintor__c,
                Primary_Outreach_Coordintor__r.Name
            FROM HOMETracker__Property__c
            WHERE
            Active_Property__c = true
            AND Current_Outreach_Timeline__r.Next_Step__c != 'DONE'
            ORDER BY Development_Address__r.Primary_Case_manager__r.name asc, Development_Address__r.Name ASC, Inventory_Sort__c ASC
            ];
            
        //get all group property parent ids
        for(HOMEtracker__Property__c g : propList){
            IF(g.Group_Property__c == true || g.Group_Property_Parent__c == NULL){
            } ELSE {
            groupCheck = groupcheck + g.Group_Property_Parent__r.Id + ', ';
            }
        }
         
       
        //loop over all propeties
        for(HOMEtracker__Property__c x : propList){
            mapKeyInt = mapKeyInt + 1;
            propType = '';
            unitCount=1;
            result='';
            
            //Determine correct property ID (group property = use group property Id, unit in group property = use group property Id, single unit = use unit Id
            // propType: 0 = group property, 1 = part of group, 2 = single
            IF(x.Group_Property__c == true){
                propType = 'Group Property';
                propId = x.id;
            } ELSE {
            IF(x.Group_Property_Parent__c == NULL){
                propType = 'Single Unit';
                propId = x.id;
            } ELSE {
                propType = 'Part of Group';
                propId = x.Group_Property_Parent__r.Id;
            }
            }
           
            //ALL APPLICANTS
            //count number of times ID is found in list of IDs
            appListTotalSize = 0;
            appListTotalSize = appsAllIDs.CountMatches(propId.left(15));
            
            // APPLICANTS INVITED TO SUBMIT
            // count number of times ID is found in list of IDs
            appListInvSize = 0;
            appListInvSize = appsInvIDs.CountMatches(propId.left(15));
            
            // APPLICANTS WHO SUBMITTED
            // Total applicants minus Applicants invited only
            appListSubSize = appListTotalSize-appListInvSize;
            
            // number of child group units
            IF(x.Group_Property__c == true){
            unitCount = groupCheck.CountMatches(propId.left(15));
            } ELSE {
            unitCount = 1;
            }
            
            //determine if additional applicants are needed
            result = determinationGet(unitCount, appListTotalSize, x.Development_Address__r.Outreach_Applicant_Strategy__c);
            
            //Add columns of text to the chart. Add another s# for each piece of data in the method below (AddStringToMap)
            mapProps.put(mapKeyInt,AddStringToMap(
                /*[0]*/ x.Development_Address__r.Name,  
                /*[1]*/ x.Development_Address__r.Id,    
                /*[2]*/ x.Name,                         
                /*[3]*/ x.id,
                /*[4]*/ x.RecordType.Name,
                /*[5]*/ propType,
                /*[6]*/ String.valueOf(appListTotalSize),
                /*[7]*/ String.valueOf(appListInvSize),
                /*[8]*/ String.valueOf(appListSubSize),
                /*[9]*/ String.valueOf(unitCount),
                /*[10]*/ result,
                /*[11]*/ x.Development_Address__r.Outreach_Applicant_Strategy__c,
                /*[12]*/ x.Development_Address__r.Primary_Case_manager__r.Name
                
                ));
            }

    }

    Public String determinationGet(Integer u, Integer a, String s){  //u = units a = total applicants s = strategy
        String r = '';
        
        IF (u == 0) { r = 'No Units'; } ELSE {
        IF (a == 0) { r = 'No Applicants'; } ELSE {
        IF (s == 'Aggressive') {
            switch on u {
                when 1 { if (a < 10) { r = 'More Needed'; } ELSE { r = 'OK'; } }
                when 2 { if (a < 12) { r = 'More Needed'; } ELSE { r = 'OK'; } }
                when 3 { if (a < 15) { r = 'More Needed'; } ELSE { r = 'OK'; } }
                when 4 { if (a < 20) { r = 'More Needed'; } ELSE { r = 'OK'; } }
                when 5 { if (a < 20) { r = 'More Needed'; } ELSE { r = 'OK'; } }
                when 6 { if (a < 20) { r = 'More Needed'; } ELSE { r = 'OK'; } }
                when 7 { if (a < 25) { r = 'More Needed'; } ELSE { r = 'OK'; } }
                when 8 { if (a < 25) { r = 'More Needed'; } ELSE { r = 'OK'; } }
                when 9 { if (a < 25) { r = 'More Needed'; } ELSE { r = 'OK'; } }
                when 10 { if (a < 25) { r = 'More Needed'; } ELSE { r = 'OK'; } }
                when else { if (a < 30) { r = 'More Needed'; } ELSE { r = 'OK'; } }
                }
            } ELSE {
            IF (s == 'Minimal') {
            IF( a < u ){r = 'More Needed';} ELSE {r = 'OK';}
            } ELSE {
            IF( (a < (u * 3)) && (a < 30)){r = 'More Needed';} ELSE {r = 'OK';}
            }
            }
            }    
        }    
        return r;
    }
    Public List<String> AddStringToMap(
            String s0,
            String s1,
            String s2,
            String s3,
            String s4,
            String s5,
            String s6,
            String s7,
            String s8,
            String s9,
            String s10,
            String s11,
            String s12
            ){
        IF(s0 == NULL){s0 = '-';}
        IF(s1 == NULL){s1 = '-';}
        IF(s2 == NULL){s2 = '-';}
        IF(s3 == NULL){s3 = '-';}
        IF(s4 == NULL){s4 = '-';}
        IF(s5 == NULL){s5 = '-';}
        IF(s6 == NULL){s6 = '-';}
        IF(s7 == NULL){s7 = '-';}
        IF(s8 == NULL){s8 = '-';}
        IF(s9 == NULL){s9 = '-';}
        IF(s10 == NULL){s10 = '-';}
        IF(s11 == NULL){s11 = 'Standard';}
        IF(s12 == NULL){s12 = '-';}
        List<String> rString = new List<String>{s0,s1,s2,s3,s4,s5,s6,s7,s8,s9,s10,s11,s12};
        return rString;
        }

}