force-app/main/default/objects/HOMEtracker__Property__c/HOMEtracker__Property__c.object-meta.xml
<CustomObject>
    <label>Property</label>
    <nameField>
        <label>Property Address</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Properties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/HOMEtracker__Property__c/fields/Current_Primary_Applicant__c.field-meta.xml
<CustomField>
    <fullName>Current_Primary_Applicant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Current applicant who is marked as the primary applicant for this unit.</inlineHelpText>
    <label>Current Primary Applicant</label>
    <referenceTo>Outreach_Tracking__c</referenceTo>
    <relationshipLabel>Primary Properties</relationshipLabel>
    <relationshipName>Properties</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/HOMEtracker__Property__c/fields/Development_address__c.field-meta.xml
<CustomField>
    <fullName>Development_address__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Development Address</label>
    <referenceTo>HOMEtracker__Property__c</referenceTo>
    <relationshipLabel>Units</relationshipLabel>
    <relationshipName>Properties</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/HOMEtracker__Property__c/fields/Group_Property__c.field-meta.xml
<CustomField>
    <fullName>Group_Property__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Check this field if this property is being used to outreach for a group of similar properties in the same development.</description>
    <inlineHelpText>Check this field if this property is being used to outreach for a group of similar properties in the same development.</inlineHelpText>
    <label>Group Property?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/HOMEtracker__Service_File__c/HOMEtracker__Service_File__c.object-meta.xml
<CustomObject>
    <description>Applications for assistance, home purchases, and other services provided</description>
    <label>Service File</label>
    <nameField>
        <label>Service File Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Services</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/HOMEtracker__Service_File__c/fields/HOMEtracker__Property__c.field-meta.xml
<CustomField>
    <fullName>HOMEtracker__Property__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup the property associated with this Service File. Tip: Create a Property record first before looking it up here. Please note: The data stored in this field is linked to the HomeKeeper National Data Hub. Do not change this field or hide it from the layout.</description>
    <inlineHelpText>Lookup the property associated with this Service File.

Tip: Create a Property record first before looking it up here.</inlineHelpText>
    <label>Property</label>
    <referenceTo>HOMEtracker__Property__c</referenceTo>
    <relationshipLabel>Services</relationshipLabel>
    <relationshipName>Property_Interests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/HOMEtracker__Service_File__c/fields/Outreach_Tracking__c.field-meta.xml
<CustomField>
    <fullName>Outreach_Tracking__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Outreach Tracking</label>
    <referenceTo>Outreach_Tracking__c</referenceTo>
    <relationshipLabel>Services</relationshipLabel>
    <relationshipName>Services</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Outreach_Tracking__c/Outreach_Tracking__c.object-meta.xml
<CustomObject>
    <description>Tracking fields for outreach</description>
    <label>Outreach Tracking</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Outreach Tracking</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Outreach_Tracking__c/fields/Applicant_Stage__c.field-meta.xml
<CustomField>
    <fullName>Applicant_Stage__c</fullName>
    <formula>IF( ISNULL(Service_File__r.Cert_or_Inelig_Date__c) = false,  TEXT(Service_File__r.HOMEtracker__Status__c) ,
CASE(TEXT(Tracker_Status__c),
&apos;&apos;,&apos;NEEDS STATUS&apos;,
&apos;Flagged&apos;,&apos;FLAGGED&apos;,
&apos;Hidden&apos;,&apos;Waiting To Be Backup&apos;,
&apos;Backup&apos;,IF( TEXT(Landlord_Developer_Determination__c) =&apos;&apos;,&apos;Backup&apos;,&apos;BACKUP w DETERMINATION&apos;),
&apos;Primary&apos;,
IF(TEXT(Landlord_Developer_Determination__c) = &apos;&apos;,&apos;Needs Property Approval&apos;,
IF( ISBLANK(Date_Eligibility_Review_Began__c ),&apos;Needs CGPH Eligibility&apos;,
TEXT(Service_File__r.Application_Workflow_Status__c )
)),&apos;?&apos;))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Calculated stage in the process of the tracking workflow.</inlineHelpText>
    <label>Applicant Stage</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Outreach_Tracking__c/fields/Date_CGPH_Added_Name__c.field-meta.xml
<CustomField>
    <fullName>Date_CGPH_Added_Name__c</fullName>
    <inlineHelpText>Date CGP&amp;H added this applicant to the tracker.</inlineHelpText>
    <label>Date CGPH Added Name</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Outreach_Tracking__c/fields/Service_File__c.field-meta.xml
<CustomField>
    <fullName>Service_File__c</fullName>
    <label>Service File</label>
    <referenceTo>HOMEtracker__Service_File__c</referenceTo>
    <relationshipLabel>Outreach Tracking</relationshipLabel>
    <relationshipName>Outreach_Tracking</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Outreach_Tracking__c/fields/Tracker_Status__c.field-meta.xml
<CustomField>
    <fullName>Tracker_Status__c</fullName>
    <inlineHelpText>The status selected will determine if the applicants will show up on the tracker, and what color they will be highlighted.</inlineHelpText>
    <label>Tracker Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Primary</fullName>
            </value>
            <value>
                <fullName>Backup</fullName>
            </value>
            <value>
                <fullName>Flagged</fullName>
            </value>
            <value>
                <fullName>Hidden</fullName>
                <default>true</default>
                <label>Hidden</label>
            </value>
            <value>
                <fullName>Removed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/PropertyInventoryExt.cls
public class PropertyInventoryExt {
    Public HOMETracker__Property__c xDev {get; set;}
    Public String xDevID {get; set;}
    Public Date lastNameGivenDate {get; set;}
    Public Integer propertyApproval {get; set;}
    Public Date propertyApprovalDate {get; set;}
    
    
    public PropertyInventoryExt(PropertyInventoryController controller) {
        xDevID= apexpages.currentpage().getparameters().get('d');
        xDev= [SELECT id, Name FROM HOMEtracker__Property__c WHERE id=:xDevID LIMIT 1];


        
        List<HOMEtracker__Property__c> listLastNameGivenDate = [
            SELECT
                Id, Current_Primary_Applicant__r.Date_CGPH_Added_Name__c
            FROM 
                HOMEtracker__Property__c
            WHERE
                Development_address__r.Id = :xDevID AND
                Group_Property__c = False AND
                Current_Primary_Applicant__r.Applicant_Stage__c = 'Needs Property Approval' AND
                Current_Primary_Applicant__r.Date_CGPH_Added_Name__c != NULL
            ORDER BY
                Current_Primary_Applicant__r.Date_CGPH_Added_Name__c DESC
                LIMIT 1
                ];
                
        IF (listLastNameGivenDate.isEmpty()){
            lastNameGivenDate = NULL;
        } ELSE {
            lastNameGivenDate = listLastNameGivenDate[0].Current_Primary_Applicant__r.Date_CGPH_Added_Name__c;
        }
        
       
        
        
 /*      
    List<Outreach_Tracking__c> listLastNameGivenDate = [
            SELECT Id, Date_CGPH_Added_Name__c
            FROM Outreach_Tracking__c
            WHERE
            Service_File__r.HOMEtracker__Property__r.Development_Address__r.Id = :xDevID AND
            Tracker_Status__c = 'Primary'
            ORDER BY
            Date_CGPH_Added_Name__c DESC
                ];
    IF (listLastNameGivenDate.isEmpty()){
        lastNameGivenDate = NULL;
    } ELSE {
        lastNameGivenDate = listLastNameGivenDate[0].Date_CGPH_Added_Name__c;
    }
*/

/*   
    List<Outreach_Tracking__c> listPropertyApproval = [
            SELECT Id, Date_CGPH_Added_Name__c
            FROM Outreach_Tracking__c
            WHERE
            Service_File__r.HOMEtracker__Property__r.Development_Address__r.Id = :xDevID AND
            Applicant_Stage__c = 'Needs Property Approval' AND
            Date_CGPH_Added_Name__c != NULL
            ORDER BY
            Date_CGPH_Added_Name__c DESC
                ];  
*/
    List<HOMEtracker__Property__c> listPropertyApproval = [
        SELECT Id
        FROM HOMEtracker__Property__c
        WHERE
            Development_address__r.Id = :xDevId AND
            Group_Property__c = False AND
            Current_Primary_Applicant__r.Applicant_Stage__c = 'Needs Property Approval'
            ];           
            
      
      propertyApproval = listPropertyApproval.size();
      
                
    }

}