force-app/main/default/objects/HOMEtracker__Property__c/HOMEtracker__Property__c.object-meta.xml
<CustomObject>
    <label>Property</label>
    <nameField>
        <label>Property Address</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Properties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/HOMEtracker__Property__c/fields/HOMEtracker__Status__c.field-meta.xml
<CustomField>
    <fullName>HOMEtracker__Status__c</fullName>
    <description>Please note: The data stored in this field is linked to the HomeKeeper National Data Hub. Do not change this picklist or hide this field from the layout.

Select the status that best describes this Property. Note: The Status does not automatically sync with related Contacts or Service Files.</description>
    <inlineHelpText>Select the status that best describes this Property. Note: The Status does not automatically sync with related Contacts or Service Files.</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Planned</fullName>
            </value>
            <value>
                <fullName>Under Construction</fullName>
            </value>
            <value>
                <fullName>Available for Sale/Resale - ITS Received</fullName>
            </value>
            <value>
                <fullName>Available for Sale/Resale</fullName>
            </value>
            <value>
                <fullName>Available for Sale - part of group</fullName>
                <label>Available for Sale/Resale - Part of Group</label>
            </value>
            <value>
                <fullName>Available for Sale/Resale - On Hold</fullName>
            </value>
            <value>
                <fullName>Available for Sale - in Queue</fullName>
            </value>
            <value>
                <fullName>Applications in Progress</fullName>
            </value>
            <value>
                <fullName>Sale Pending</fullName>
            </value>
            <value>
                <fullName>Sale Pending/Cert App/No PA</fullName>
            </value>
            <value>
                <fullName>Sale Pending/Cert App/PA/No Contract</fullName>
            </value>
            <value>
                <fullName>Sale Pending/In Escrow</fullName>
                <label>Sale Pending/In Escrow with Contract</label>
            </value>
            <value>
                <fullName>Owner Occupied</fullName>
            </value>
            <value>
                <fullName>Not Owner Occupied - Leased to Tenant</fullName>
            </value>
            <value>
                <fullName>Available For Rent</fullName>
                <label>Available for Rent</label>
            </value>
            <value>
                <fullName>Available for Rent - part of group</fullName>
                <label>Available for Rent - Part of Group</label>
            </value>
            <value>
                <fullName>Available for Rent - On Hold</fullName>
            </value>
            <value>
                <fullName>Available for Rent - in Queue</fullName>
            </value>
            <value>
                <fullName>Rental Pending</fullName>
            </value>
            <value>
                <fullName>Rented</fullName>
            </value>
            <value>
                <fullName>Lease Purchase Occupancy</fullName>
            </value>
            <value>
                <fullName>Estate</fullName>
            </value>
            <value>
                <fullName>Bank Owned</fullName>
            </value>
            <value>
                <fullName>Abandoned</fullName>
            </value>
            <value>
                <fullName>Initial Sales in Progress</fullName>
                <label>Initial Sales - In Progress</label>
            </value>
            <value>
                <fullName>Initial Sale of Units Completed</fullName>
                <label>Initial Sales - Completed</label>
            </value>
            <value>
                <fullName>Initial Rental/Sale On-hold bc nonresponsive</fullName>
            </value>
            <value>
                <fullName>Sold Out of Program</fullName>
            </value>
            <value>
                <fullName>Subdivided</fullName>
            </value>
            <value>
                <fullName>Initial lease up in progress</fullName>
                <label>Initial Lease Up - In Progress</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/HOMEtracker__Property__c/fields/Municipality_Name__c.field-meta.xml
<CustomField>
    <fullName>Municipality_Name__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Municipality</label>
    <referenceTo>Municipality__c</referenceTo>
    <relationshipLabel>Properties</relationshipLabel>
    <relationshipName>Properties</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/HOMEtracker__Service_File__c/HOMEtracker__Service_File__c.object-meta.xml
<CustomObject>
    <description>Applications for assistance, home purchases, and other services provided</description>
    <label>Service File</label>
    <nameField>
        <label>Service File Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Services</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/HOMEtracker__Service_File__c/fields/HOMEtracker__Property__c.field-meta.xml
<CustomField>
    <fullName>HOMEtracker__Property__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup the property associated with this Service File. Tip: Create a Property record first before looking it up here. Please note: The data stored in this field is linked to the HomeKeeper National Data Hub. Do not change this field or hide it from the layout.</description>
    <inlineHelpText>Lookup the property associated with this Service File.

Tip: Create a Property record first before looking it up here.</inlineHelpText>
    <label>Property</label>
    <referenceTo>HOMEtracker__Property__c</referenceTo>
    <relationshipLabel>Services</relationshipLabel>
    <relationshipName>Property_Interests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/HOMEtracker__Service_File__c/fields/HOMEtracker__Status__c.field-meta.xml
<CustomField>
    <fullName>HOMEtracker__Status__c</fullName>
    <description>Please note: The data stored in this field is linked to the HomeKeeper National Data Hub. Please contact support if you want to add a new status. Select the current Status of this Service File. Tip: To update the status of the Service File, Property and Applicant Contact records at the same time, click the Update Status button.</description>
    <inlineHelpText>Tracks the status of the Service File. 

Tip: To update the status of the Service File, Property and Applicant Contact records at the same time, click the Update Status button.</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Pending Direct Application Invitation</fullName>
            </value>
            <value>
                <fullName>Application In Process - Alternate Property</fullName>
                <label>Application in Process - Alternate Property</label>
            </value>
            <value>
                <fullName>Application in Process - Docs Old</fullName>
            </value>
            <value>
                <fullName>Application in Process</fullName>
            </value>
            <value>
                <fullName>Failed Pre-Screen</fullName>
            </value>
            <value>
                <fullName>Failed Income Certification - Pending Appeal</fullName>
                <color>#FF0000</color>
                <label>Failed Income Certification - Pending Appeal</label>
            </value>
            <value>
                <fullName>Failed Income Certification</fullName>
                <color>#CC0000</color>
                <label>Failed Income Certification</label>
            </value>
            <value>
                <fullName>Withdrawn / No Longer Interested</fullName>
                <color>#CC33CC</color>
                <label>Withdrawn - No Longer Interested</label>
            </value>
            <value>
                <fullName>Withdrawn - Backup (Did Not Start Certification)</fullName>
                <label>Withdrawn - Did Not Start Certification (Backup, Duplicate, Switched Unit, No Supporting Docs)</label>
            </value>
            <value>
                <fullName>Withdrawn, Did Not Submit Application</fullName>
            </value>
            <value>
                <fullName>Certified - Pending Final Documents</fullName>
                <color>#FFCC33</color>
                <label>Certified - Pending Final Documents</label>
            </value>
            <value>
                <fullName>Certified - Pending Closing</fullName>
                <color>#33CC00</color>
                <label>Certified - Pending Closing</label>
            </value>
            <value>
                <fullName>Certified - Backup</fullName>
            </value>
            <value>
                <fullName>Certified - On Hold</fullName>
                <color>#6666CC</color>
                <label>Certified - On Hold</label>
            </value>
            <value>
                <fullName>Certified - Expired</fullName>
                <color>#6633FF</color>
                <label>Certified - Expired</label>
            </value>
            <value>
                <fullName>Current Owner</fullName>
                <color>#33CC00</color>
                <label>Current Owner</label>
            </value>
            <value>
                <fullName>Current Renter</fullName>
                <color>#FFCC33</color>
                <label>Current Renter</label>
            </value>
            <value>
                <fullName>Past Owner</fullName>
                <color>#33CC00</color>
                <label>Past Owner</label>
            </value>
            <value>
                <fullName>Past Renter</fullName>
                <color>#FFCC33</color>
                <label>Past Renter</label>
            </value>
            <value>
                <fullName>Application Complete</fullName>
            </value>
            <value>
                <fullName>Assistance Complete</fullName>
            </value>
            <value>
                <fullName>Ineligible</fullName>
            </value>
            <value>
                <fullName>Wait List</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Recertification - Certified</fullName>
            </value>
            <value>
                <fullName>Recertification - Ineligible</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/HOMEtracker__Service_File__c/fields/Municipality__c.field-meta.xml
<CustomField>
    <fullName>Municipality__c</fullName>
    <formula>HOMEtracker__Property__r.Municipality_Name__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Municipality</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/AALogExt_Event_TEST.cls
@istest
public class AALogExt_Event_TEST {
	private static testmethod void AALogExt_Event_TEST(){
		
        Municipality__c objMuni = new Municipality__c();
		objMuni.Name = 'Test Muni';
		insert objMuni;
        
        HOMEtracker__Property__c objProp = new HOMEtracker__Property__c();
        objProp.Name = 'TEST';
        objProp.Municipality_Name__c = objMuni.Id;
        objProp.HOMEtracker__Status__c = 'Planned';
        insert objProp;
        
        HOMEtracker__Service_File__c objSF = new HOMEtracker__Service_File__c();
        objSF.Name = 'TEST';
        insert objSF;
        HOMEtracker__Monitoring_Event__c objEvent = new HOMEtracker__Monitoring_Event__c();
        objEvent.HOMEtracker__Monitoring_Event_Type__c = 'Other';
        objEvent.HOMEtracker__Service_File__c = objSF.id;
        objEvent.HOMEtracker__Status__c = 'Active';
        insert objEvent;

		ApexPages.currentPage().getParameters().put('id', objEvent.id);
		ApexPages.StandardController std = new ApexPages.StandardController(objEvent);
	    AALogExt_Event AALogExt_Event_TEST  = new AALogExt_Event(std);

    }
}