force-app/main/default/objects/HOMEtracker__Property__c/HOMEtracker__Property__c.object-meta.xml
<CustomObject>
    <label>Property</label>
    <nameField>
        <label>Property Address</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Properties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/HOMEtracker__Property__c/fields/Development_address__c.field-meta.xml
<CustomField>
    <fullName>Development_address__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Development Address</label>
    <referenceTo>HOMEtracker__Property__c</referenceTo>
    <relationshipLabel>Units</relationshipLabel>
    <relationshipName>Properties</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/HOMEtracker__Property__c/recordTypes/Development.recordType-meta.xml
<RecordType>
    <fullName>Development</fullName>
    <active>true</active>
    <description>This is the Administrative Agent Development Property. It is manually created by a staff member.</description>
    <label>Development</label>
</RecordType>

force-app/main/default/objects/HOMEtracker__Service_File__c/HOMEtracker__Service_File__c.object-meta.xml
<CustomObject>
    <description>Applications for assistance, home purchases, and other services provided</description>
    <label>Service File</label>
    <nameField>
        <label>Service File Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Services</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/HOMEtracker__Service_File__c/fields/HOMEtracker__Property__c.field-meta.xml
<CustomField>
    <fullName>HOMEtracker__Property__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup the property associated with this Service File. Tip: Create a Property record first before looking it up here. Please note: The data stored in this field is linked to the HomeKeeper National Data Hub. Do not change this field or hide it from the layout.</description>
    <inlineHelpText>Lookup the property associated with this Service File.

Tip: Create a Property record first before looking it up here.</inlineHelpText>
    <label>Property</label>
    <referenceTo>HOMEtracker__Property__c</referenceTo>
    <relationshipLabel>Services</relationshipLabel>
    <relationshipName>Property_Interests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/HOMEtracker__Service_File__c/fields/Municipality__c.field-meta.xml
<CustomField>
    <fullName>Municipality__c</fullName>
    <formula>HOMEtracker__Property__r.Municipality_Name__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Municipality</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/HOMEtracker__Service_File__c/fields/Outreach_Tracking__c.field-meta.xml
<CustomField>
    <fullName>Outreach_Tracking__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Outreach Tracking</label>
    <referenceTo>Outreach_Tracking__c</referenceTo>
    <relationshipLabel>Services</relationshipLabel>
    <relationshipName>Services</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/HOMEtracker__Service_File__c/fields/Unit__c.field-meta.xml
<CustomField>
    <fullName>Unit__c</fullName>
    <inlineHelpText>Enter the unit number for the property that this applicant is applying to. This is used on the tracker.</inlineHelpText>
    <label>Unit</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/HOMEtracker__Service_File__c/recordTypes/Rental.recordType-meta.xml
<RecordType>
    <fullName>Rental</fullName>
    <active>true</active>
    <label>Rental</label>
</RecordType>

force-app/main/default/objects/Outreach_Tracking__c/Outreach_Tracking__c.object-meta.xml
<CustomObject>
    <description>Tracking fields for outreach</description>
    <label>Outreach Tracking</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Outreach Tracking</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Outreach_Tracking__c/fields/Date_CGPH_Added_Name__c.field-meta.xml
<CustomField>
    <fullName>Date_CGPH_Added_Name__c</fullName>
    <inlineHelpText>Date CGP&amp;H added this applicant to the tracker.</inlineHelpText>
    <label>Date CGPH Added Name</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Outreach_Tracking__c/fields/Date_Marked_Primary__c.field-meta.xml
<CustomField>
    <fullName>Date_Marked_Primary__c</fullName>
    <inlineHelpText>The date this applicant was marked as a primary applicant.</inlineHelpText>
    <label>Date Marked Primary</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Outreach_Tracking__c/fields/Landlord_Developer_App_Sent__c.field-meta.xml
<CustomField>
    <fullName>Landlord_Developer_App_Sent__c</fullName>
    <inlineHelpText>Text provided by landlord / developer / seller if a their application was sent, and when. Yes or No can be answer, or a date.</inlineHelpText>
    <label>Landlord / Developer App Sent</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Outreach_Tracking__c/fields/Landlord_Developer_Deadline__c.field-meta.xml
<CustomField>
    <fullName>Landlord_Developer_Deadline__c</fullName>
    <inlineHelpText>Deadline landlord / developer has given applicant to complete their application process.</inlineHelpText>
    <label>Landlord / Developer Deadline</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Outreach_Tracking__c/fields/Landlord_Developer_Determination__c.field-meta.xml
<CustomField>
    <fullName>Landlord_Developer_Determination__c</fullName>
    <inlineHelpText>Approval or Denial provided by landlord / developer</inlineHelpText>
    <label>Landlord / Developer Determination</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Denied</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Outreach_Tracking__c/fields/Landlord_Developer_Determination_Date__c.field-meta.xml
<CustomField>
    <fullName>Landlord_Developer_Determination_Date__c</fullName>
    <inlineHelpText>Date landlord / developer determined the applicant was acceptable or not.</inlineHelpText>
    <label>Landlord / Developer Determination Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Outreach_Tracking__c/fields/Landlord_Developer_Last_Update__c.field-meta.xml
<CustomField>
    <fullName>Landlord_Developer_Last_Update__c</fullName>
    <inlineHelpText>Auto-filled by submitted Landlord / Developer form</inlineHelpText>
    <label>Landlord / Developer Last Update</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Outreach_Tracking__c/fields/Landlord_Developer_Notes__c.field-meta.xml
<CustomField>
    <fullName>Landlord_Developer_Notes__c</fullName>
    <inlineHelpText>Notes provided by landlord / developer regarding applicant.</inlineHelpText>
    <label>Landlord / Developer Notes</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Outreach_Tracking__c/fields/Landlord_Developer_Tour__c.field-meta.xml
<CustomField>
    <fullName>Landlord_Developer_Tour__c</fullName>
    <inlineHelpText>Text provided by landlord / developer if a tour occurred, and when. Yes or No can be answer, or a date.</inlineHelpText>
    <label>Landlord / Developer Tour</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Outreach_Tracking__c/fields/Property_Unit__c.field-meta.xml
<CustomField>
    <fullName>Property_Unit__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Enter the property here, of if part of a group listing enter the appropriate property unit once applicable.</inlineHelpText>
    <label>Property / Unit</label>
    <referenceTo>HOMEtracker__Property__c</referenceTo>
    <relationshipLabel>Outreach Tracking</relationshipLabel>
    <relationshipName>Outreach_Tracking</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Outreach_Tracking__c/fields/Service_File__c.field-meta.xml
<CustomField>
    <fullName>Service_File__c</fullName>
    <label>Service File</label>
    <referenceTo>HOMEtracker__Service_File__c</referenceTo>
    <relationshipLabel>Outreach Tracking</relationshipLabel>
    <relationshipName>Outreach_Tracking</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Outreach_Tracking__c/fields/Tracker_Status__c.field-meta.xml
<CustomField>
    <fullName>Tracker_Status__c</fullName>
    <inlineHelpText>The status selected will determine if the applicants will show up on the tracker, and what color they will be highlighted.</inlineHelpText>
    <label>Tracker Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Primary</fullName>
            </value>
            <value>
                <fullName>Backup</fullName>
            </value>
            <value>
                <fullName>Flagged</fullName>
            </value>
            <value>
                <fullName>Hidden</fullName>
                <default>true</default>
                <label>Hidden</label>
            </value>
            <value>
                <fullName>Removed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Outreach_Tracking__c/fields/Unit__c.field-meta.xml
<CustomField>
    <fullName>Unit__c</fullName>
    <inlineHelpText>If applicable, enter a unit number that this applicant is in consideration for</inlineHelpText>
    <label>Unit</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/OutreachListAAContTest.cls
@istest
public class OutreachListAAContTest {
    
    static testMethod void EdisonAHP_PropOnlyContTest(){
        Income_Limits__c r1IncomeLimit = CGPHTestFactory.createIncomeLimit('1');
        PreApplicants__c applicant1 = CGPHTestFactory.createPreapplicant(true,false,true);
        Municipality__c objmunicipality1 = CGPHTestFactory.createMunicipalityObject('Township1','1',false,false,'All AR','All AR',true,true,0,'Moderate;Low;Very Low','Moderate;Low;Very Low');//condition1
        HOMEtracker__Property__c development = CGPHTestFactory.createProperty(objmunicipality1.id,'Development','Available For Rent');
        HOMEtracker__Property__c property = CGPHTestFactory.createProperty(objmunicipality1.id,'Rental Unit','Available For Rent');
        property.Development_address__c = development.Id;
        update property;
        
        HOMEtracker__Service_File__c sf = new HOMEtracker__Service_File__c();
        insert sf;
            
        Outreach_Tracking__c ot = new Outreach_Tracking__c();
        ot.Date_CGPH_Added_Name__c = System.today();
        ot.Date_Marked_Primary__c = System.today();
        ot.Landlord_Developer_App_Sent__c = 'true';
        ot.Landlord_Developer_Deadline__c = System.today();
        ot.Landlord_Developer_Determination_Date__c = System.today();
        ot.Landlord_Developer_Determination__c = 'Approved';
        ot.Landlord_Developer_Last_Update__c = System.now();
        ot.Landlord_Developer_Notes__c = 'test';
        ot.Landlord_Developer_Tour__c = 'test';
        ot.Name = 'test name';
        ot.Property_Unit__c = property.id;
        ot.Service_File__c = sf.id;
        ot.Tracker_Status__c = 'Primary';
        ot.Unit__c = '1';
        insert ot;
        
        
        OutreachListAACont controller = new OutreachListAACont();
        String result = controller.result;
        
    }

}