force-app/main/default/objects/HOMEtracker__Property__c/HOMEtracker__Property__c.object-meta.xml
<CustomObject>
    <label>Property</label>
    <nameField>
        <label>Property Address</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Properties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/HOMEtracker__Property__c/fields/Municipality_Name__c.field-meta.xml
<CustomField>
    <fullName>Municipality_Name__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Municipality</label>
    <referenceTo>Municipality__c</referenceTo>
    <relationshipLabel>Properties</relationshipLabel>
    <relationshipName>Properties</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/HOMEtracker__Service_File__c/HOMEtracker__Service_File__c.object-meta.xml
<CustomObject>
    <description>Applications for assistance, home purchases, and other services provided</description>
    <label>Service File</label>
    <nameField>
        <label>Service File Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Services</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/HOMEtracker__Service_File__c/fields/HOMEtracker__Property__c.field-meta.xml
<CustomField>
    <fullName>HOMEtracker__Property__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup the property associated with this Service File. Tip: Create a Property record first before looking it up here. Please note: The data stored in this field is linked to the HomeKeeper National Data Hub. Do not change this field or hide it from the layout.</description>
    <inlineHelpText>Lookup the property associated with this Service File.

Tip: Create a Property record first before looking it up here.</inlineHelpText>
    <label>Property</label>
    <referenceTo>HOMEtracker__Property__c</referenceTo>
    <relationshipLabel>Services</relationshipLabel>
    <relationshipName>Property_Interests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/HOMEtracker__Service_File__c/fields/Municipality__c.field-meta.xml
<CustomField>
    <fullName>Municipality__c</fullName>
    <formula>HOMEtracker__Property__r.Municipality_Name__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Municipality</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/HOMEtracker__Service_File__c/fields/Pre_Applicant__c.field-meta.xml
<CustomField>
    <fullName>Pre_Applicant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Pre-Applicant</label>
    <referenceTo>PreApplicants__c</referenceTo>
    <relationshipLabel>Full Applications</relationshipLabel>
    <relationshipName>Services</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/OutreachApplicantsExtTest.cls
@ISTEST
public class OutreachApplicantsExtTest {
	static testMethod void OutreachApplicantsExtTest(){
    	
		Campaign objCampaign = new Campaign();
        objCampaign.Name='Test';
		insert objCampaign;
        String CampID = objCampaign.id;
        
        Account newAccount = new Account();
        newAccount.Name = 'test account';
        insert newAccount;
        String acctID = newAccount.id;
        
        Contact newContact = new Contact();
        newContact.FirstName = 'John';
        newContact.LastName = 'Test';
        insert newContact;
        
        String contactID = newContact.Id;
        
    	CampaignMember objCampaignMember = new CampaignMember();
        objCampaignMember.ContactId = contactId;
        objCampaignMember.Status = 'Emailed';
        objCampaignMember.CampaignId = CampID;
		insert objCampaignMember;

        Municipality__c objMuni = new Municipality__c();
        objMuni.Name = 'Test Muni';
        insert objMuni;
                    
       	HOMETRACKER__Property__c objProp = new HOMETRACKER__Property__c();
        objProp.name = 'Test Property';
        objProp.Municipality_Name__c = objMuni.Id;
        insert objProp;

		HOMEtracker__Service_File__c objSF = new HOMEtracker__Service_File__c();
        objSF.RecordTypeId = '012o00000003fYBAAY';
        objSF.Name = 'test SF';
        objSF.HOMEtracker__Property__c = objProp.Id;
        insert objSF;

        PreApplicants__c objPreApp = new PreApplicants__c();
        objPreApp.name='test';
        Insert objPreApp;
        
        Application__c objPS = new Application__c();
        objPS.Name = 'test';
        objPS.Pre_Applicant__c = objPreApp.Id;
        objPS.RecordTypeId = '012o000000048DLAAY';
        insert objPS;
        
		ApexPages.StandardController std = new ApexPages.StandardController(objProp);
	    OutreachApplicantsExt OutreachApplicantsExtTest  = new OutreachApplicantsExt(std);
	}
}