force-app/main/default/objects/HOMEtracker__Property__c/HOMEtracker__Property__c.object-meta.xml
<CustomObject>
    <label>Property</label>
    <nameField>
        <label>Property Address</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Properties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/HOMEtracker__Property__c/fields/Google_Tracker_Link__c.field-meta.xml
<CustomField>
    <fullName>Google_Tracker_Link__c</fullName>
    <label>Google Tracker Link</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/HOMEtracker__Property__c/fields/Outreach_Contact__c.field-meta.xml
<CustomField>
    <fullName>Outreach_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Outreach department&apos;s day-to-day contact person.</description>
    <inlineHelpText>Outreach department&apos;s day-to-day contact person.</inlineHelpText>
    <label>Day-to-Day Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Properties (Outreach Contact)</relationshipLabel>
    <relationshipName>Properties7</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/HOMEtracker__Property__c/fields/Primary_Case_manager__c.field-meta.xml
<CustomField>
    <fullName>Primary_Case_manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Primary Case Manager</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.RecordType.Name</field>
            <operation>equals</operation>
            <value>Professional</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Properties (Primary Case manager)</relationshipLabel>
    <relationshipName>Properties2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/HOMEtracker__Property__c/fields/Publish_Outreach_Tracker__c.field-meta.xml
<CustomField>
    <fullName>Publish_Outreach_Tracker__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>If this is checked, the public Outreach Tracker will be available to view outside the company</inlineHelpText>
    <label>Publish Outreach Tracker</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/HOMEtracker__Property__c/fields/Publish_Property_Inventory__c.field-meta.xml
<CustomField>
    <fullName>Publish_Property_Inventory__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>If this is checked, the public Property Inventory will be available to view outside the company</inlineHelpText>
    <label>Publish Property Inventory</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/HOMEtracker__Service_File__c/HOMEtracker__Service_File__c.object-meta.xml
<CustomObject>
    <description>Applications for assistance, home purchases, and other services provided</description>
    <label>Service File</label>
    <nameField>
        <label>Service File Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Services</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/HOMEtracker__Service_File__c/fields/HOMEtracker__Property__c.field-meta.xml
<CustomField>
    <fullName>HOMEtracker__Property__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup the property associated with this Service File. Tip: Create a Property record first before looking it up here. Please note: The data stored in this field is linked to the HomeKeeper National Data Hub. Do not change this field or hide it from the layout.</description>
    <inlineHelpText>Lookup the property associated with this Service File.

Tip: Create a Property record first before looking it up here.</inlineHelpText>
    <label>Property</label>
    <referenceTo>HOMEtracker__Property__c</referenceTo>
    <relationshipLabel>Services</relationshipLabel>
    <relationshipName>Property_Interests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/HOMEtracker__Service_File__c/fields/Outreach_Tracking__c.field-meta.xml
<CustomField>
    <fullName>Outreach_Tracking__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Outreach Tracking</label>
    <referenceTo>Outreach_Tracking__c</referenceTo>
    <relationshipLabel>Services</relationshipLabel>
    <relationshipName>Services</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/HOMEtracker__Service_File__c/fields/Priority__c.field-meta.xml
<CustomField>
    <fullName>Priority__c</fullName>
    <description>Enter the order the applications should be resolved.</description>
    <inlineHelpText>Enter the order the applications should be resolved.</inlineHelpText>
    <label>Outreach Priority</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/HOMEtracker__Service_File__c/fields/Property_Id__c.field-meta.xml
<CustomField>
    <fullName>Property_Id__c</fullName>
    <formula>HOMEtracker__Property__r.Id</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Property Id</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/HOMEtracker__Service_File__c/fields/Unit__c.field-meta.xml
<CustomField>
    <fullName>Unit__c</fullName>
    <inlineHelpText>Enter the unit number for the property that this applicant is applying to. This is used on the tracker.</inlineHelpText>
    <label>Unit</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Outreach_Tracking__c/Outreach_Tracking__c.object-meta.xml
<CustomObject>
    <description>Tracking fields for outreach</description>
    <label>Outreach Tracking</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Outreach Tracking</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Outreach_Tracking__c/fields/Applicant_Email__c.field-meta.xml
<CustomField>
    <fullName>Applicant_Email__c</fullName>
    <formula>Service_File__r.HOMEtracker__Applicant__r.Email</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Applicant Email</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Outreach_Tracking__c/fields/Applicant_Name__c.field-meta.xml
<CustomField>
    <fullName>Applicant_Name__c</fullName>
    <formula>Service_File__r.HOMEtracker__Applicant__r.FirstName &amp;&quot; &quot;&amp; Service_File__r.HOMEtracker__Applicant__r.LastName</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Applicant Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Outreach_Tracking__c/fields/Applicant_Phone__c.field-meta.xml
<CustomField>
    <fullName>Applicant_Phone__c</fullName>
    <formula>Service_File__r.HOMEtracker__Applicant__r.Phone</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Applicant Phone</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Outreach_Tracking__c/fields/CGPH_Approval_Denial_Date__c.field-meta.xml
<CustomField>
    <fullName>CGPH_Approval_Denial_Date__c</fullName>
    <formula>Service_File__r.Cert_or_Inelig_Date__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>From Service File</inlineHelpText>
    <label>CGPH Approval / Denial Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Outreach_Tracking__c/fields/CGPH_Determination__c.field-meta.xml
<CustomField>
    <fullName>CGPH_Determination__c</fullName>
    <formula>Service_File__r.Certified_or_Ineligible__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>From Service File</inlineHelpText>
    <label>CGPH Determination</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Outreach_Tracking__c/fields/Date_CGPH_Added_Name__c.field-meta.xml
<CustomField>
    <fullName>Date_CGPH_Added_Name__c</fullName>
    <inlineHelpText>Date CGP&amp;H added this applicant to the tracker.</inlineHelpText>
    <label>Date CGPH Added Name</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Outreach_Tracking__c/fields/Date_Eligibility_Review_Began__c.field-meta.xml
<CustomField>
    <fullName>Date_Eligibility_Review_Began__c</fullName>
    <formula>Service_File__r.Income_Certification_Start_Date__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>From Service File</inlineHelpText>
    <label>Date Eligibility Review Began</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Outreach_Tracking__c/fields/Date_Ready_for_Eligibility_Review__c.field-meta.xml
<CustomField>
    <fullName>Date_Ready_for_Eligibility_Review__c</fullName>
    <formula>Service_File__r.Ready_for_Full_Income_Cert_Date__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Date Ready for Eligibility Review</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Outreach_Tracking__c/fields/Household_Size__c.field-meta.xml
<CustomField>
    <fullName>Household_Size__c</fullName>
    <formula>Service_File__r.HOMEtracker__Household_Size__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>From Service File</inlineHelpText>
    <label>Household Size</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Outreach_Tracking__c/fields/Landlord_Developer_App_Sent__c.field-meta.xml
<CustomField>
    <fullName>Landlord_Developer_App_Sent__c</fullName>
    <inlineHelpText>Text provided by landlord / developer / seller if a their application was sent, and when. Yes or No can be answer, or a date.</inlineHelpText>
    <label>Landlord / Developer App Sent</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Outreach_Tracking__c/fields/Landlord_Developer_Deadline__c.field-meta.xml
<CustomField>
    <fullName>Landlord_Developer_Deadline__c</fullName>
    <inlineHelpText>Deadline landlord / developer has given applicant to complete their application process.</inlineHelpText>
    <label>Landlord / Developer Deadline</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Outreach_Tracking__c/fields/Landlord_Developer_Determination__c.field-meta.xml
<CustomField>
    <fullName>Landlord_Developer_Determination__c</fullName>
    <inlineHelpText>Approval or Denial provided by landlord / developer</inlineHelpText>
    <label>Landlord / Developer Determination</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Denied</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Outreach_Tracking__c/fields/Landlord_Developer_Determination_Date__c.field-meta.xml
<CustomField>
    <fullName>Landlord_Developer_Determination_Date__c</fullName>
    <inlineHelpText>Date landlord / developer determined the applicant was acceptable or not.</inlineHelpText>
    <label>Landlord / Developer Determination Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Outreach_Tracking__c/fields/Landlord_Developer_Notes__c.field-meta.xml
<CustomField>
    <fullName>Landlord_Developer_Notes__c</fullName>
    <inlineHelpText>Notes provided by landlord / developer regarding applicant.</inlineHelpText>
    <label>Landlord / Developer Notes</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Outreach_Tracking__c/fields/Landlord_Developer_Tour__c.field-meta.xml
<CustomField>
    <fullName>Landlord_Developer_Tour__c</fullName>
    <inlineHelpText>Text provided by landlord / developer if a tour occurred, and when. Yes or No can be answer, or a date.</inlineHelpText>
    <label>Landlord / Developer Tour</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Outreach_Tracking__c/fields/Priority_Calc__c.field-meta.xml
<CustomField>
    <fullName>Priority_Calc__c</fullName>
    <formula>IF( Service_File__r.Priority__c =0,1000, Service_File__r.Priority__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Priority Calc</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Outreach_Tracking__c/fields/Property_Address__c.field-meta.xml
<CustomField>
    <fullName>Property_Address__c</fullName>
    <formula>Service_File__r.HOMEtracker__Property__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Property Address</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Outreach_Tracking__c/fields/Property_Id__c.field-meta.xml
<CustomField>
    <fullName>Property_Id__c</fullName>
    <formula>IF( ISBLANK(Service_File__r.HOMEtracker__Property__r.Group_Property_Parent__c ),Service_File__r.HOMEtracker__Property__r.Id,Service_File__r.HOMEtracker__Property__r.Group_Property_Parent__r.Id)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>If part of group property, show group property ID, if not then show property ID</inlineHelpText>
    <label>Property Id Group</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Outreach_Tracking__c/fields/Property_Rent_or_List_Price__c.field-meta.xml
<CustomField>
    <fullName>Property_Rent_or_List_Price__c</fullName>
    <formula>MAX(Service_File__r.HOMEtracker__Property__r.HOMEtracker__Monthly_Rent__c,
Service_File__r.HOMEtracker__Property__r.HOMEtracker__List_Price__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Property Rent or List Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Outreach_Tracking__c/fields/SF_Priority__c.field-meta.xml
<CustomField>
    <fullName>SF_Priority__c</fullName>
    <formula>Service_File__r.Priority__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>SF Priority</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Outreach_Tracking__c/fields/Unit__c.field-meta.xml
<CustomField>
    <fullName>Unit__c</fullName>
    <inlineHelpText>If applicable, enter a unit number that this applicant is in consideration for</inlineHelpText>
    <label>Unit</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/OutreachTrackerController.cls
public class OutreachTrackerController {
    Public HOMETracker__Property__c dev {get; set;}
    Public List<Outreach_Tracking__c> result {get; set;}
    Public String devID {get; set;}
    
    public OutreachTrackerController(){
        
        devID= apexpages.currentpage().getparameters().get('d');
        
        dev= [SELECT
              id,
              Name,
              Google_Tracker_Link__c,
              Primary_Case_manager__c,
              Primary_Case_manager__r.FirstName,
              Primary_Case_manager__r.LastName,
              Primary_Case_manager__r.Email,
              Publish_Outreach_Tracker__c,
              Publish_Property_Inventory__c,
              Outreach_Contact__r.FirstName,
              Outreach_Contact__r.LastName,
              Outreach_Contact__r.email
              FROM HOMEtracker__Property__c WHERE id=:devID];
    }
    public Map<String,ListWrapper> getotByProperty(){
        
        result = 
            [SELECT Id,
             Name,
             Property_Id__c,
             Property_Address__c,
             Unit__c,
             Property_Rent_or_List_Price__c,
             SF_Priority__c,
             Priority_Calc__c,
             Applicant_Name__c,
             Applicant_Email__c,
             Applicant_Phone__c,
             Household_Size__c,
             Date_CGPH_Added_Name__c,
             Date_Eligibility_Review_Began__c,
             Date_Ready_for_Eligibility_Review__c,
             CGPH_Determination__c,
             CGPH_Approval_Denial_Date__c,
             Landlord_Developer_Tour__c,
             Landlord_Developer_Notes__c,
             Landlord_Developer_Determination_Date__c,
             Landlord_Developer_Determination__c,
             Landlord_Developer_Deadline__c,
             Landlord_Developer_App_Sent__c,
             Tracker_Status__c,
             Service_File__r.Priority__c
             FROM Outreach_Tracking__c
             WHERE Service_File__r.HOMETracker__Property__r.Include_on_Tracker__c=true AND
             Include_On_Tracker__c = true AND
             Service_File__r.HOMETracker__Property__r.Development_address__r.Id = :devID
             ORDER BY
             Priority_Calc__c ASC];
        
        // Group Outreach Tracking by Property
        Map<String,ListWrapper> otByProperty= new Map<String,ListWrapper>();
        for(Outreach_Tracking__c ot: result){
            if(null == ot.Property_Id__c) continue;
            ListWrapper var1 = otByProperty.get(ot.Property_Id__c);
            if(null == var1){
                otByProperty.put(ot.Property_Id__c, new ListWrapper(new List<Outreach_Tracking__c>()) );    
            }
            otByProperty.get(ot.Property_Id__c).otList.add(ot);
        }
        
        return otByProperty;
        
        
    }
    
    
    // List of Outreach Tracking and details  
    class ListWrapper {
        
        public List<Outreach_Tracking__c> otList{get; set;}
        
        public Integer numOfOTs{
            get{
                return otList.size();
            }
            set;
        }
        
        public Id firstOfList{
            get{
                return otList[0].Id;
            }
            set;
        }
        
        public ListWrapper(List<Outreach_Tracking__c> listOTs){
            
            otList= listOTs;
            
        }
        
    }
    
    
}