force-app/main/default/objects/HOMEtracker__Property__c/HOMEtracker__Property__c.object-meta.xml
<CustomObject>
    <label>Property</label>
    <nameField>
        <label>Property Address</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Properties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/HOMEtracker__Property__c/fields/Current_Outreach_Timeline__c.field-meta.xml
<CustomField>
    <fullName>Current_Outreach_Timeline__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Current Outreach Timeline</label>
    <referenceTo>Outreach_Timeline__c</referenceTo>
    <relationshipLabel>Properties</relationshipLabel>
    <relationshipName>Properties</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/HOMEtracker__Property__c/fields/Group_Property_Parent__c.field-meta.xml
<CustomField>
    <fullName>Group_Property_Parent__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>If this property is a single unit that is part of a group property for outreach, enter the group property that it is a part of in this field.</inlineHelpText>
    <label>Group Property</label>
    <referenceTo>HOMEtracker__Property__c</referenceTo>
    <relationshipLabel>Properties (Group Property)</relationshipLabel>
    <relationshipName>Group_Properties</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/HOMEtracker__Property__c/fields/Include_on_Tracker__c.field-meta.xml
<CustomField>
    <fullName>Include_on_Tracker__c</fullName>
    <defaultValue>true</defaultValue>
    <inlineHelpText>Include this property on the tracker sent to developer / landlord / owner.</inlineHelpText>
    <label>Include on Tracker</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/HOMEtracker__Service_File__c/HOMEtracker__Service_File__c.object-meta.xml
<CustomObject>
    <description>Applications for assistance, home purchases, and other services provided</description>
    <label>Service File</label>
    <nameField>
        <label>Service File Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Services</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/HOMEtracker__Service_File__c/fields/Application_Workflow_Status__c.field-meta.xml
<CustomField>
    <fullName>Application_Workflow_Status__c</fullName>
    <description>Used to track staff&apos;s progress through the income certification process.</description>
    <inlineHelpText>Tracks the status of the certification process.</inlineHelpText>
    <label>Application Workflow Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Invited - Waiting to Submit</fullName>
            </value>
            <value>
                <fullName>Waiting for Rental Pre-Screen</fullName>
            </value>
            <value>
                <fullName>Failed Pre-Screen</fullName>
            </value>
            <value>
                <fullName>Pre-Screen Complete, Not Yet Referred</fullName>
            </value>
            <value>
                <fullName>Application Received - Waiting for Credit Results</fullName>
                <label>Application Received - Waiting for Credit / Developer</label>
            </value>
            <value>
                <fullName>Application Received - Missing Mortgage Pre-Approval</fullName>
            </value>
            <value>
                <fullName>Application Received - Backup Ready for Full Income Certification</fullName>
                <color>#FFCC66</color>
                <label>Application Received - Backup Ready for Full Income Certification</label>
            </value>
            <value>
                <fullName>Application Received - Ready for Full Income Certification</fullName>
                <color>#F3D904</color>
                <label>Application Received - Ready for Full Income Certification</label>
            </value>
            <value>
                <fullName>Application Received - Full Income Certification In Progress</fullName>
                <color>#3366FF</color>
                <label>Application Received - Full Income Certification In Progress</label>
            </value>
            <value>
                <fullName>Application Received - Ready for Peer Review</fullName>
                <color>#9999FF</color>
                <label>Application Received - Ready for Peer Review</label>
            </value>
            <value>
                <fullName>Application Received - Peer Review In Progress</fullName>
                <color>#CC33CC</color>
                <label>Application Received - Peer Review In Progress</label>
            </value>
            <value>
                <fullName>Application Received - Peer Review Completed</fullName>
                <color>#993399</color>
                <label>Application Received - Peer Review Completed</label>
            </value>
            <value>
                <fullName>Application Received - Peer Review Completed - On Hold</fullName>
                <color>#663366</color>
                <label>Application Received - Peer Review Completed - On Hold</label>
            </value>
            <value>
                <fullName>Application Received - Updating After Peer Review</fullName>
                <color>#339999</color>
                <label>Application Received - Updating After Peer Review</label>
            </value>
            <value>
                <fullName>Application Received - Certification Completed</fullName>
                <color>#78C953</color>
                <label>Application Received - Certification Completed</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/HOMEtracker__Service_File__c/fields/HOMEtracker__Property__c.field-meta.xml
<CustomField>
    <fullName>HOMEtracker__Property__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup the property associated with this Service File. Tip: Create a Property record first before looking it up here. Please note: The data stored in this field is linked to the HomeKeeper National Data Hub. Do not change this field or hide it from the layout.</description>
    <inlineHelpText>Lookup the property associated with this Service File.

Tip: Create a Property record first before looking it up here.</inlineHelpText>
    <label>Property</label>
    <referenceTo>HOMEtracker__Property__c</referenceTo>
    <relationshipLabel>Services</relationshipLabel>
    <relationshipName>Property_Interests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/HOMEtracker__Service_File__c/fields/Include_on_Tracker__c.field-meta.xml
<CustomField>
    <fullName>Include_on_Tracker__c</fullName>
    <formula>AND(
OR(
AND(CONTAINS(TEXT(Application_Workflow_Status__c ),&apos;Application Received&apos;),NOT(Contains(TEXT(Application_Workflow_Status__c ),&apos;Backup&apos;))),
OR(
TEXT( HOMEtracker__Status__c )= &apos;Application in Process&apos;,
TEXT( HOMEtracker__Status__c )= &apos;Application in Process - Alternate Property&apos;,
TEXT( HOMEtracker__Status__c )= &apos;Application in Process - Old Docs&apos;
)
),
AND(
NOT(TEXT( HOMEtracker__Status__c )=&apos;Current Owner&apos;),
NOT(TEXT( HOMEtracker__Status__c )=&apos;Current Renter&apos;),
NOT(TEXT( HOMEtracker__Status__c )=&apos;Failed Income Certification&apos;),
NOT(TEXT( HOMEtracker__Status__c )=&apos;Failed Pre-Screen&apos;),
NOT(TEXT( HOMEtracker__Status__c )=&apos;Past Renter&apos;),
NOT(TEXT( HOMEtracker__Status__c )=&apos;&apos;),
NOT(CONTAINS(TEXT( HOMEtracker__Status__c ),&apos;Withdrawn&apos;))
)
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Include on Tracker</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/HOMEtracker__Service_File__c/fields/Outreach_Tracking__c.field-meta.xml
<CustomField>
    <fullName>Outreach_Tracking__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Outreach Tracking</label>
    <referenceTo>Outreach_Tracking__c</referenceTo>
    <relationshipLabel>Services</relationshipLabel>
    <relationshipName>Services</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Outreach_Tracking__c/Outreach_Tracking__c.object-meta.xml
<CustomObject>
    <description>Tracking fields for outreach</description>
    <label>Outreach Tracking</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Outreach Tracking</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Outreach_Tracking__c/fields/Include_on_Tracker__c.field-meta.xml
<CustomField>
    <fullName>Include_on_Tracker__c</fullName>
    <formula>AND(
Service_File__r.HOMEtracker__Property__r.Include_on_Tracker__c=true,
OR(
TEXT(Tracker_Status__c) =&apos;Primary&apos;,
TEXT(Tracker_Status__c)=&apos;Backup&apos;,
TEXT(Tracker_Status__c)=&apos;Flagged&apos;,
TEXT(Tracker_Status__c)=&apos;Hidden&apos;,
AND(TEXT(Tracker_Status__c)=&apos;Removed&apos;, Move_to_Removed_Report__c = false)),
Priority_Calc__c != 1000,
NOT(TEXT( Service_File__r.HOMEtracker__Status__c )=&apos;Current Owner&apos;),
NOT(TEXT( Service_File__r.HOMEtracker__Status__c )=&apos;Current Renter&apos;),
NOT(TEXT( Service_File__r.HOMEtracker__Status__c )=&apos;Past Renter&apos;),
NOT(TEXT( Service_File__r.HOMEtracker__Status__c )=&apos;&apos;),
NOT(CONTAINS(TEXT( Service_File__r.HOMEtracker__Status__c ),&apos;Withdrawn&apos;))
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Calculated from Service File Status Fields.</inlineHelpText>
    <label>Available for Tracker</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Outreach_Tracking__c/fields/Service_File__c.field-meta.xml
<CustomField>
    <fullName>Service_File__c</fullName>
    <label>Service File</label>
    <referenceTo>HOMEtracker__Service_File__c</referenceTo>
    <relationshipLabel>Outreach Tracking</relationshipLabel>
    <relationshipName>Outreach_Tracking</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/AvailableApplicantsExt.cls
public class AvailableApplicantsExt {
    public List<Outreach_Tracking__c> listApplicants {get; set;}
    public List<Outreach_Tracking__c> listInvited {get; set;}
    public List<HOMEtracker__Property__c> listUnits {get; set;}
    public HOMETRACKER__Property__c property {get; set;}
    public HOMETRACKER__Property__c property2 {get; set;}
    public Integer countApplicants {get; set;}
    public Integer countInvited {get; set;}
    public Integer countSubmitted {get; set;}
    public Integer countUnits {get; set;}   
    public String finalID {get; set;}
    public String uType {get; set;}
    public String urlType {get; set;}
    public String aShow {get; set;}
    
    public AvailableApplicantsExt(ApexPages.StandardController controller) {
        property = (HOMETracker__Property__c )controller.getRecord();
        urlType = apexpages.currentpage().getparameters().get('t');
        aShow = apexpages.currentpage().getparameters().get('a');
        
        property2 = [SELECT id, Group_Property_Parent__r.Id from HOMEtracker__Property__c WHERE id = :property.Id LIMIT 1];
                
        finalID = '';
        uType='x';
        listUnits = NULL;
        countApplicants=0;
        countInvited=0;
        countSubmitted=0;
        countUnits=0;
        
        // If property is a group property //
        IF(urlType == 'g' ){
            finalID = property2.Id;
            uType='g';
            listUnits = [SELECT 
                                id,
                                Group_Property_Parent__r.Id,
                                Group_Property_Parent__c 
                         FROM
                                HOMEtracker__Property__c
                         WHERE
                                Group_Property_Parent__r.Id = :finalID AND
                                Current_Outreach_Timeline__r.Next_Step__c != 'DONE'
                        ];
            IF (listUnits.size() == 0) {
                countUnits=0;
                listUnits = NULL;
                } ELSE {
                countUnits = listUnits.size();
                }
        } ELSE {
        
        // If property is a Single Unit not in Group Property //
        IF(urlType == 's'){
            finalID = property2.Id;
            uType='s';
            listUnits = NULL;
        } ELSE {
            
        // If property is a Unit in Group Property //
            finalID = property2.Group_Property_Parent__r.Id;
            uType='pg';
            listUnits = NULL;
        }
        }
        
        // TOTAL APPLICANTS //
        listApplicants = [
                SELECT id
                FROM Outreach_Tracking__c
                WHERE Service_File__r.HOMEtracker__Property__r.Id = :finalID AND Include_On_Tracker__c = true
            ];
        
        IF (listApplicants.size() == 0) {
            countApplicants=0;
            listApplicants = NULL;
        } ELSE {
            countApplicants = listApplicants.size();
        }
        
        
        // APPLICANTS INVITED TO SUBMIT //
        listInvited = [
                SELECT id
                FROM Outreach_Tracking__c
                WHERE Service_File__r.HOMEtracker__Property__r.Id = :finalID AND
                    Include_On_Tracker__c = true AND
                    Service_File__r.Application_Workflow_Status__c = 'Invited - Waiting to Submit'                    
            ];
        
        IF (listInvited.size() == 0) {
            countInvited=0;
            listInvited = NULL;
        } ELSE {
            countInvited = listInvited.size();
        }
        
        //APPLICANTS WHO SUBMITTED (calculated)//
        countSubmitted = countApplicants - countInvited;

        
    
        
        
        
        
        
    }
}