force-app/main/default/objects/HOMEtracker__Property__c/HOMEtracker__Property__c.object-meta.xml
<CustomObject>
    <label>Property</label>
    <nameField>
        <label>Property Address</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Properties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Outreach_Tracking__c/Outreach_Tracking__c.object-meta.xml
<CustomObject>
    <description>Tracking fields for outreach</description>
    <label>Outreach Tracking</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Outreach Tracking</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Outreach_Tracking__c/fields/Applicant_Name__c.field-meta.xml
<CustomField>
    <fullName>Applicant_Name__c</fullName>
    <formula>Service_File__r.HOMEtracker__Applicant__r.FirstName &amp;&quot; &quot;&amp; Service_File__r.HOMEtracker__Applicant__r.LastName</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Applicant Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Outreach_Tracking__c/fields/CGPH_Approval_Denial_Date__c.field-meta.xml
<CustomField>
    <fullName>CGPH_Approval_Denial_Date__c</fullName>
    <formula>Service_File__r.Cert_or_Inelig_Date__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>From Service File</inlineHelpText>
    <label>CGPH Approval / Denial Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Outreach_Tracking__c/fields/CGPH_Determination__c.field-meta.xml
<CustomField>
    <fullName>CGPH_Determination__c</fullName>
    <formula>Service_File__r.Certified_or_Ineligible__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>From Service File</inlineHelpText>
    <label>CGPH Determination</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Outreach_Tracking__c/fields/Date_CGPH_Added_Name__c.field-meta.xml
<CustomField>
    <fullName>Date_CGPH_Added_Name__c</fullName>
    <inlineHelpText>Date CGP&amp;H added this applicant to the tracker.</inlineHelpText>
    <label>Date CGPH Added Name</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Outreach_Tracking__c/fields/Date_Eligibility_Review_Began__c.field-meta.xml
<CustomField>
    <fullName>Date_Eligibility_Review_Began__c</fullName>
    <formula>Service_File__r.Income_Certification_Start_Date__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>From Service File</inlineHelpText>
    <label>Date Eligibility Review Began</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Outreach_Tracking__c/fields/Date_Marked_Primary__c.field-meta.xml
<CustomField>
    <fullName>Date_Marked_Primary__c</fullName>
    <inlineHelpText>The date this applicant was marked as a primary applicant.</inlineHelpText>
    <label>Date Marked Primary</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Outreach_Tracking__c/fields/Date_Ready_for_Eligibility_Review__c.field-meta.xml
<CustomField>
    <fullName>Date_Ready_for_Eligibility_Review__c</fullName>
    <formula>Service_File__r.Ready_for_Full_Income_Cert_Date__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Date Ready for Eligibility Review</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Outreach_Tracking__c/fields/Landlord_Developer_Determination__c.field-meta.xml
<CustomField>
    <fullName>Landlord_Developer_Determination__c</fullName>
    <inlineHelpText>Approval or Denial provided by landlord / developer</inlineHelpText>
    <label>Landlord / Developer Determination</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Denied</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Outreach_Tracking__c/fields/Landlord_Developer_Determination_Date__c.field-meta.xml
<CustomField>
    <fullName>Landlord_Developer_Determination_Date__c</fullName>
    <inlineHelpText>Date landlord / developer determined the applicant was acceptable or not.</inlineHelpText>
    <label>Landlord / Developer Determination Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Outreach_Tracking__c/fields/Landlord_Developer_Notes__c.field-meta.xml
<CustomField>
    <fullName>Landlord_Developer_Notes__c</fullName>
    <inlineHelpText>Notes provided by landlord / developer regarding applicant.</inlineHelpText>
    <label>Landlord / Developer Notes</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Outreach_Tracking__c/fields/Priority_Calc__c.field-meta.xml
<CustomField>
    <fullName>Priority_Calc__c</fullName>
    <formula>IF( Service_File__r.Priority__c =0,1000, Service_File__r.Priority__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Priority Calc</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Outreach_Tracking__c/fields/Property_Address__c.field-meta.xml
<CustomField>
    <fullName>Property_Address__c</fullName>
    <formula>Service_File__r.HOMEtracker__Property__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Property Address</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Outreach_Tracking__c/fields/Property_Unit__c.field-meta.xml
<CustomField>
    <fullName>Property_Unit__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Enter the property here, of if part of a group listing enter the appropriate property unit once applicable.</inlineHelpText>
    <label>Property / Unit</label>
    <referenceTo>HOMEtracker__Property__c</referenceTo>
    <relationshipLabel>Outreach Tracking</relationshipLabel>
    <relationshipName>Outreach_Tracking</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Outreach_Tracking__c/fields/SF_Priority__c.field-meta.xml
<CustomField>
    <fullName>SF_Priority__c</fullName>
    <formula>Service_File__r.Priority__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>SF Priority</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Outreach_Tracking__c/fields/Tracker_Status__c.field-meta.xml
<CustomField>
    <fullName>Tracker_Status__c</fullName>
    <inlineHelpText>The status selected will determine if the applicants will show up on the tracker, and what color they will be highlighted.</inlineHelpText>
    <label>Tracker Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Primary</fullName>
            </value>
            <value>
                <fullName>Backup</fullName>
            </value>
            <value>
                <fullName>Flagged</fullName>
            </value>
            <value>
                <fullName>Hidden</fullName>
                <default>true</default>
                <label>Hidden</label>
            </value>
            <value>
                <fullName>Removed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Outreach_Tracking__c/fields/Unit__c.field-meta.xml
<CustomField>
    <fullName>Unit__c</fullName>
    <inlineHelpText>If applicable, enter a unit number that this applicant is in consideration for</inlineHelpText>
    <label>Unit</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/OutreachTrackerUnitExt.cls
public class OutreachTrackerUnitExt {
    public Outreach_Tracking__c primary {get; set;}
    public HOMETRACKER__Property__c property {get; set;}
    
    public OutreachTrackerUnitExt(ApexPages.StandardController controller) {
    
    property = (HOMETracker__Property__c )controller.getRecord();
    
    List<Outreach_Tracking__c> listPrimary = 
                [
                SELECT id
                FROM Outreach_Tracking__c
                WHERE Property_Unit__r.Id = :property.Id
                ORDER BY Priority_Calc__c ASC
                ];
    
    IF (listPrimary.size() == 0) {
    primary = NULL;
    } ELSE {
    
    primary = [
                SELECT
                id,
                Name,
                Applicant_Name__c,
                Tracker_Status__c,
                Property_Unit__c,
                Property_Address__c,
                Unit__c,
                SF_Priority__c,
                Date_CGPH_Added_Name__c,
                Date_Marked_Primary__c,
                Landlord_Developer_Determination__c,
                Landlord_Developer_Determination_Date__c,
                Landlord_Developer_Notes__c,
                Date_Ready_for_Eligibility_Review__c,
                Date_Eligibility_Review_Began__c,
                CGPH_Determination__c,
                CGPH_Approval_Denial_Date__c
                
                FROM Outreach_Tracking__c
                WHERE Property_Unit__r.Id = :property.Id
                ORDER BY Priority_Calc__c ASC
                LIMIT 1
              ];
        }          
             

    }

}