force-app/main/default/objects/HOMEtracker__Property__c/HOMEtracker__Property__c.object-meta.xml
<CustomObject>
    <label>Property</label>
    <nameField>
        <label>Property Address</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Properties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/HOMEtracker__Property__c/fields/Devel_Visible_on_Website__c.field-meta.xml
<CustomField>
    <fullName>Devel_Visible_on_Website__c</fullName>
    <defaultValue>false</defaultValue>
    <description>If this box is checked, its Development Page will be visible on our website.</description>
    <inlineHelpText>If this box is checked, its Development Page will be visible on our website.</inlineHelpText>
    <label>Visible on Website?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/HOMEtracker__Property__c/fields/Development_address__c.field-meta.xml
<CustomField>
    <fullName>Development_address__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Development Address</label>
    <referenceTo>HOMEtracker__Property__c</referenceTo>
    <relationshipLabel>Units</relationshipLabel>
    <relationshipName>Properties</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/HOMEtracker__Property__c/fields/HOMEtracker__Status__c.field-meta.xml
<CustomField>
    <fullName>HOMEtracker__Status__c</fullName>
    <description>Please note: The data stored in this field is linked to the HomeKeeper National Data Hub. Do not change this picklist or hide this field from the layout.

Select the status that best describes this Property. Note: The Status does not automatically sync with related Contacts or Service Files.</description>
    <inlineHelpText>Select the status that best describes this Property. Note: The Status does not automatically sync with related Contacts or Service Files.</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Planned</fullName>
            </value>
            <value>
                <fullName>Under Construction</fullName>
            </value>
            <value>
                <fullName>Available for Sale/Resale - ITS Received</fullName>
            </value>
            <value>
                <fullName>Available for Sale/Resale</fullName>
            </value>
            <value>
                <fullName>Available for Sale - part of group</fullName>
                <label>Available for Sale/Resale - Part of Group</label>
            </value>
            <value>
                <fullName>Available for Sale/Resale - On Hold</fullName>
            </value>
            <value>
                <fullName>Available for Sale - in Queue</fullName>
            </value>
            <value>
                <fullName>Applications in Progress</fullName>
            </value>
            <value>
                <fullName>Sale Pending</fullName>
            </value>
            <value>
                <fullName>Sale Pending/Cert App/No PA</fullName>
            </value>
            <value>
                <fullName>Sale Pending/Cert App/PA/No Contract</fullName>
            </value>
            <value>
                <fullName>Sale Pending/In Escrow</fullName>
                <label>Sale Pending/In Escrow with Contract</label>
            </value>
            <value>
                <fullName>Owner Occupied</fullName>
            </value>
            <value>
                <fullName>Not Owner Occupied - Leased to Tenant</fullName>
            </value>
            <value>
                <fullName>Available For Rent</fullName>
                <label>Available for Rent</label>
            </value>
            <value>
                <fullName>Available for Rent - part of group</fullName>
                <label>Available for Rent - Part of Group</label>
            </value>
            <value>
                <fullName>Available for Rent - On Hold</fullName>
            </value>
            <value>
                <fullName>Available for Rent - in Queue</fullName>
            </value>
            <value>
                <fullName>Rental Pending</fullName>
            </value>
            <value>
                <fullName>Rented</fullName>
            </value>
            <value>
                <fullName>Lease Purchase Occupancy</fullName>
            </value>
            <value>
                <fullName>Estate</fullName>
            </value>
            <value>
                <fullName>Bank Owned</fullName>
            </value>
            <value>
                <fullName>Abandoned</fullName>
            </value>
            <value>
                <fullName>Initial Sales in Progress</fullName>
                <label>Initial Sales - In Progress</label>
            </value>
            <value>
                <fullName>Initial Sale of Units Completed</fullName>
                <label>Initial Sales - Completed</label>
            </value>
            <value>
                <fullName>Initial Rental/Sale On-hold bc nonresponsive</fullName>
            </value>
            <value>
                <fullName>Sold Out of Program</fullName>
            </value>
            <value>
                <fullName>Subdivided</fullName>
            </value>
            <value>
                <fullName>Initial lease up in progress</fullName>
                <label>Initial Lease Up - In Progress</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/HOMEtracker__Property__c/fields/Municipality_Name__c.field-meta.xml
<CustomField>
    <fullName>Municipality_Name__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Municipality</label>
    <referenceTo>Municipality__c</referenceTo>
    <relationshipLabel>Properties</relationshipLabel>
    <relationshipName>Properties</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/HOMEtracker__Property__c/fields/Rental_or_Sale_Development__c.field-meta.xml
<CustomField>
    <fullName>Rental_or_Sale_Development__c</fullName>
    <label>Rental or Sale Development</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Rental</fullName>
            </value>
            <value>
                <fullName>Sale</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/CGPHAllDevelopmentsController.cls
public class CGPHAllDevelopmentsController {
    public Map<String,Map<String,Map<String,Map<String,String>>>> mapPurchaseDevelopmentsByCounty {get;set;}
    public Map<String,Map<String,Map<String,Map<String,String>>>> mapRentalDevelopmentsByCounty {get;set;}
    public Map<String,Map<String,Map<String,Map<String,String>>>> mapAllDevelopmentsByCounty {get;set;}
    public Map<String,Map<String,Map<String,String>>> mapRentalDevelopmentsByMuni {get;set;}
    public Map<String,Map<String,Map<String,String>>> mapPurchaseDevelopmentsByMuni {get;set;}
    public Map<String,Map<String,Map<String,String>>> mapAllDevelopmentsByMuni {get;set;}
    public Map<String,Map<String,Map<String,String>>> mapRentalDevelopmentsByAlpha {get;set;}
    public Map<String,Map<String,Map<String,String>>> mapPurchaseDevelopmentsByAlpha {get;set;}
    public Map<String,Map<String,Map<String,String>>> mapAllDevelopmentsByAlpha {get;set;}
    public Map<String,Boolean> mapRentalIdx {get;set;}
    public Map<String,Boolean> mapPurchaseIdx {get;set;}
    public Map<String,Boolean> mapAllIdx {get;set;}
    public String defType {get;set;}
    public String defBy {get;set;}

    //method to show rental devlopments
    public CGPHAllDevelopmentsController(){
        	//param pass through
        	defType = System.currentPageReference().getParameters().get('typ');
        	defBy = System.currentPageReference().getParameters().get('by');

			mapPurchaseDevelopmentsByCounty = mapPurchaseDevelopmentsByCounty();
            mapRentalDevelopmentsByCounty = mapRentalDevelopmentsByCounty();
        	mapAllDevelopmentsByCounty = mapAllDevelopmentsByCounty();
        	mapPurchaseDevelopmentsByMuni = mapPurchaseDevelopmentsByMuni();
            mapRentalDevelopmentsByMuni = mapRentalDevelopmentsByMuni();
        	mapAllDevelopmentsByMuni = mapAllDevelopmentsByMuni();
        	mapPurchaseDevelopmentsByAlpha = mapPurchaseDevelopmentsByAlpha();
            mapRentalDevelopmentsByAlpha = mapRentalDevelopmentsByAlpha();
        	mapAllDevelopmentsByAlpha = mapAllDevelopmentsByAlpha();
	}
    
    
    public Map<String,Map<String,Map<String,Map<String,String>>>> mapDevelopmentsByCounty(string PropertyType) {
        Map<String,Map<String,Map<String,Map<String,String>>>> mapAllCounties = new Map<String,Map<String,Map<String,Map<String,String>>>>();
        String devSOQL =	'SELECT Id, Municipality_Name__c, Municipality_Name__r.Id, Municipality_Name__r.County__c, ';
            devSOQL +=		'Municipality_Name__r.Municipality_Name_Calc__c, Name, ';
        	devSOQL +=		'HOMEtracker__Status__c ';
            devSOQL +=		'FROM HOMEtracker__Property__c ';
            devSOQL +=		'WHERE ';
        if (PropertyType != 'All') {
            devSOQL +=		'(Rental_or_Sale_Development__c = :PropertyType) AND ';
        }
        	devSOQL += 		'Development_address__c = null AND ';
        	devSOQL += 		'Devel_Visible_on_Website__c = TRUE AND ';
            devSOQL += 		'Municipality_Name__r.Muni_Visible_on_Website__c = TRUE ';
            devSOQL +=		'ORDER BY Municipality_Name__r.County__c, Municipality_Name__r.Municipality_Name_Calc__c, Name';
        
        Map<ID, HOMEtracker__Property__c> mapDevelopments = new Map<ID, HOMEtracker__Property__c>(
            (List<HOMEtracker__Property__c>)Database.query(devSOQL)
		);

        if(mapDevelopments != null && mapDevelopments.size() > 0) {
			for (HOMEtracker__Property__c property : mapDevelopments.values()) {
                Municipality__c pmuni = property.Municipality_Name__r;
                if ( !mapAllCounties.containsKey(pmuni.County__c)  ) {
                    mapAllCounties.put(pmuni.County__c, new Map<String,Map<String,Map<String,String>>>());
                }
                Map<String,Map<String,Map<String,String>>> county = mapAllCounties.get(pmuni.County__c);
                if ( !county.containsKey(pmuni.Municipality_Name_Calc__c) ) {
                    county.put(pmuni.Municipality_Name_Calc__c, new Map<String,Map<String,String>>());
                }
                Map<String,Map<String,String>> municipality = county.get(pmuni.Municipality_Name_Calc__c);
                Map<String,String> propertyMap = new Map<String,String>();
                propertyMap.put('id', property.Id);
                propertyMap.put('mid', property.Municipality_Name__r.Id);
                propertyMap.put('name', property.Name);
                propertyMap.put('not_admin', property.HOMEtracker__Status__c
                             				== 'Not administered directly by CGP&H' ? 'true' : 'false');
                Pattern notAN = Pattern.compile('[^a-zA-Z0-9]');
                Matcher rmatch = notAN.matcher(property.Name + property.Id);
                municipality.put(rmatch.replaceAll(''), propertyMap);
            }
    	}
        return mapAllCounties;
    }
    
    public Map<String,Map<String,Map<String,Map<String,String>>>> mapPurchaseDevelopmentsByCounty() {
        return mapDevelopmentsByCounty('Sale');
    }
    public Map<String,Map<String,Map<String,Map<String,String>>>> mapRentalDevelopmentsByCounty() {
        return mapDevelopmentsByCounty('Rental');
    }
    public Map<String,Map<String,Map<String,Map<String,String>>>> mapAllDevelopmentsByCounty() {
        return mapDevelopmentsByCounty('All');
    }

    public Map<String,Map<String,Map<String,String>>> mapDevelopmentsByMuni(string PropertyType) {
        Map<String,Map<String,Map<String,String>>> mapAllMuni = new Map<String,Map<String,Map<String,String>>>();
        String devSOQL =	'SELECT Id, Municipality_Name__c, Municipality_Name__r.Id, Municipality_Name__r.County__c, ';
            devSOQL +=		'Municipality_Name__r.Municipality_Name_Calc__c, Name, ';
            devSOQL +=		'HOMEtracker__Status__c ';
            devSOQL +=		'FROM HOMEtracker__Property__c ';
            devSOQL +=		'WHERE ';
        if (PropertyType != 'All') {
            devSOQL +=		'(Rental_or_Sale_Development__c = :PropertyType) AND ';
        }
            devSOQL +=		'Development_address__c = null AND ';
            devSOQL +=		'Devel_Visible_on_Website__c = TRUE AND ';
            devSOQL +=		'Municipality_Name__r.Muni_Visible_on_Website__c = TRUE ';
            devSOQL +=		'ORDER BY Municipality_Name__r.Municipality_Name_Calc__c, Name';
        
        Map<ID, HOMEtracker__Property__c> mapDevelopments = new Map<ID, HOMEtracker__Property__c>(
            (List<HOMEtracker__Property__c>)Database.query(devSOQL)
		);

        if(mapDevelopments != null && mapDevelopments.size() > 0) {
			for (HOMEtracker__Property__c property : mapDevelopments.values()) {
                Municipality__c pmuni = property.Municipality_Name__r;
                if ( !mapAllMuni.containsKey(pmuni.Municipality_Name_Calc__c)  ) {
                    mapAllMuni.put(pmuni.Municipality_Name_Calc__c, new Map<String,Map<String,String>>());
                }
                Map<String,Map<String,String>> municipality = mapAllMuni.get(pmuni.Municipality_Name_Calc__c);
                Map<String,String> propertyMap = new Map<String,String>();
                propertyMap.put('id', property.Id);
                propertyMap.put('mid', property.Municipality_Name__r.Id);
                propertyMap.put('name', property.Name);
                propertyMap.put('not_admin', property.HOMEtracker__Status__c
                             				== 'Not administered directly by CGP&H' ? 'true' : 'false');
                Pattern notAN = Pattern.compile('[^a-zA-Z0-9]');
                Matcher rmatch = notAN.matcher(property.Name + property.Id);
                municipality.put(rmatch.replaceAll(''), propertyMap);
            }
    	}
        return mapAllMuni;
    }
    
    public Map<String,Map<String,Map<String,String>>> mapPurchaseDevelopmentsByMuni() {
        return mapDevelopmentsByMuni('Sale');
    }
    public Map<String,Map<String,Map<String,String>>> mapRentalDevelopmentsByMuni() {
        return mapDevelopmentsByMuni('Rental');
    }
    public Map<String,Map<String,Map<String,String>>> mapAllDevelopmentsByMuni() {
        return mapDevelopmentsByMuni('All');
    }
    
    public Map<String,Map<String,Map<String,String>>> mapDevelopmentsByAlpha(string PropertyType) {
        Map<String,Map<String,Map<String,String>>> mapAllAlpha = new Map<String,Map<String,Map<String,String>>>();
        Map<String,Boolean> mapAlpha = new Map<String,Boolean>();
        
        String alphaList = '#ABCDEFGHIJKLMNOPOQRSTUVWXYZ';
        for (Integer c = 0; c < alphaList.length(); c++) {
            mapAlpha.put(alphaList.substring(c,c+1), false);
        }
        
        String devSOQL =	'SELECT Id, Municipality_Name__c, Municipality_Name__r.Id, Municipality_Name__r.County__c, ';
            devSOQL +=		'Municipality_Name__r.Municipality_Name_Calc__c, Name, ';
        	devSOQL +=		'HOMEtracker__Status__c ';
            devSOQL +=		'FROM HOMEtracker__Property__c ';
            devSOQL +=		'WHERE ';
        if (PropertyType != 'All') {
            devSOQL +=		'(Rental_or_Sale_Development__c = :PropertyType) AND ';
        }
            devSOQL += 		'Development_address__c = null AND ';
        	devSOQL += 		'Devel_Visible_on_Website__c = TRUE AND ';
        	devSOQL += 		'Municipality_Name__r.Muni_Visible_on_Website__c = TRUE ';
            devSOQL +=		'ORDER BY Municipality_Name__r.Municipality_Name_Calc__c, Name';
        
        Map<ID, HOMEtracker__Property__c> mapDevelopments = new Map<ID, HOMEtracker__Property__c>(
            (List<HOMEtracker__Property__c>)Database.query(devSOQL)
		);

        if(mapDevelopments != null && mapDevelopments.size() > 0) {
			for (HOMEtracker__Property__c property : mapDevelopments.values()) {
                String palpha = property.Name.substring(0,1).toUpperCase().replaceAll('[0-9]','#');
                mapAlpha.put(palpha, true);
                if ( !mapAllAlpha.containsKey(palpha)  ) {
                    mapAllAlpha.put(palpha, new Map<String,Map<String,String>>());
                }
                Map<String,Map<String,String>> alpha = mapAllAlpha.get(palpha);
                Map<String,String> propertyMap = new Map<String,String>();
                propertyMap.put('id', property.Id);
                propertyMap.put('mid', property.Municipality_Name__r.Id);
                propertyMap.put('name', property.Name);
                propertyMap.put('not_admin', property.HOMEtracker__Status__c
                             				== 'Not administered directly by CGP&H' ? 'true' : 'false');
                Pattern notAN = Pattern.compile('[^a-zA-Z0-9]');
                Matcher rmatch = notAN.matcher(property.Name + property.Id);
                alpha.put(rmatch.replaceAll(''), propertyMap);
            }
    	}

        switch on PropertyType {
            when 'Sale' {
                mapPurchaseIdx = mapAlpha;
            }
            when 'Rental' {
                mapRentalIdx = mapAlpha;
            }
            when 'All' {
                mapAllIdx = mapAlpha;
            }
        }

        return mapAllAlpha;
    }

    
    public Map<String,Map<String,Map<String,String>>> mapPurchaseDevelopmentsByAlpha() {
        return mapDevelopmentsByAlpha('Sale');
    }
    public Map<String,Map<String,Map<String,String>>> mapRentalDevelopmentsByAlpha() {
        return mapDevelopmentsByAlpha('Rental');
    }
    public Map<String,Map<String,Map<String,String>>> mapAllDevelopmentsByAlpha() {
        return mapDevelopmentsByAlpha('All');
    }

}