force-app/main/default/objects/HOMEtracker__Property__c/HOMEtracker__Property__c.object-meta.xml
<CustomObject>
    <label>Property</label>
    <nameField>
        <label>Property Address</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Properties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/HOMEtracker__Property__c/fields/Unit_Number__c.field-meta.xml
<CustomField>
    <fullName>Unit_Number__c</fullName>
    <inlineHelpText>Unit number of home if applicable</inlineHelpText>
    <label>Unit Number</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/HOMEtracker__Property__c/recordTypes/Development.recordType-meta.xml
<RecordType>
    <fullName>Development</fullName>
    <active>true</active>
    <description>This is the Administrative Agent Development Property. It is manually created by a staff member.</description>
    <label>Development</label>
</RecordType>

force-app/main/default/objects/HOMEtracker__Service_File__c/HOMEtracker__Service_File__c.object-meta.xml
<CustomObject>
    <description>Applications for assistance, home purchases, and other services provided</description>
    <label>Service File</label>
    <nameField>
        <label>Service File Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Services</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/HOMEtracker__Service_File__c/fields/Outreach_Tracking__c.field-meta.xml
<CustomField>
    <fullName>Outreach_Tracking__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Outreach Tracking</label>
    <referenceTo>Outreach_Tracking__c</referenceTo>
    <relationshipLabel>Services</relationshipLabel>
    <relationshipName>Services</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/HOMEtracker__Service_File__c/fields/Priority__c.field-meta.xml
<CustomField>
    <fullName>Priority__c</fullName>
    <description>Enter the order the applications should be resolved.</description>
    <inlineHelpText>Enter the order the applications should be resolved.</inlineHelpText>
    <label>Outreach Priority</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/HOMEtracker__Service_File__c/fields/Property_Id__c.field-meta.xml
<CustomField>
    <fullName>Property_Id__c</fullName>
    <formula>HOMEtracker__Property__r.Id</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Property Id</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/HOMEtracker__Service_File__c/fields/Unit__c.field-meta.xml
<CustomField>
    <fullName>Unit__c</fullName>
    <inlineHelpText>Enter the unit number for the property that this applicant is applying to. This is used on the tracker.</inlineHelpText>
    <label>Unit</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Outreach_Tracking__c/Outreach_Tracking__c.object-meta.xml
<CustomObject>
    <description>Tracking fields for outreach</description>
    <label>Outreach Tracking</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Outreach Tracking</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Outreach_Tracking__c/fields/Applicant_Email__c.field-meta.xml
<CustomField>
    <fullName>Applicant_Email__c</fullName>
    <formula>Service_File__r.HOMEtracker__Applicant__r.Email</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Applicant Email</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Outreach_Tracking__c/fields/Applicant_Name__c.field-meta.xml
<CustomField>
    <fullName>Applicant_Name__c</fullName>
    <formula>Service_File__r.HOMEtracker__Applicant__r.FirstName &amp;&quot; &quot;&amp; Service_File__r.HOMEtracker__Applicant__r.LastName</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Applicant Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Outreach_Tracking__c/fields/Applicant_Phone__c.field-meta.xml
<CustomField>
    <fullName>Applicant_Phone__c</fullName>
    <formula>Service_File__r.HOMEtracker__Applicant__r.Phone</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Applicant Phone</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Outreach_Tracking__c/fields/CGPH_Approval_Denial_Date__c.field-meta.xml
<CustomField>
    <fullName>CGPH_Approval_Denial_Date__c</fullName>
    <formula>Service_File__r.Cert_or_Inelig_Date__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>From Service File</inlineHelpText>
    <label>CGPH Approval / Denial Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Outreach_Tracking__c/fields/CGPH_Determination__c.field-meta.xml
<CustomField>
    <fullName>CGPH_Determination__c</fullName>
    <formula>Service_File__r.Certified_or_Ineligible__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>From Service File</inlineHelpText>
    <label>CGPH Determination</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Outreach_Tracking__c/fields/Date_CGPH_Added_Name__c.field-meta.xml
<CustomField>
    <fullName>Date_CGPH_Added_Name__c</fullName>
    <inlineHelpText>Date CGP&amp;H added this applicant to the tracker.</inlineHelpText>
    <label>Date CGPH Added Name</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Outreach_Tracking__c/fields/Date_Eligibility_Review_Began__c.field-meta.xml
<CustomField>
    <fullName>Date_Eligibility_Review_Began__c</fullName>
    <formula>Service_File__r.Income_Certification_Start_Date__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>From Service File</inlineHelpText>
    <label>Date Eligibility Review Began</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Outreach_Tracking__c/fields/Date_Marked_Primary__c.field-meta.xml
<CustomField>
    <fullName>Date_Marked_Primary__c</fullName>
    <inlineHelpText>The date this applicant was marked as a primary applicant.</inlineHelpText>
    <label>Date Marked Primary</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Outreach_Tracking__c/fields/Date_Ready_for_Eligibility_Review__c.field-meta.xml
<CustomField>
    <fullName>Date_Ready_for_Eligibility_Review__c</fullName>
    <formula>Service_File__r.Ready_for_Full_Income_Cert_Date__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Date Ready for Eligibility Review</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Outreach_Tracking__c/fields/Household_Size__c.field-meta.xml
<CustomField>
    <fullName>Household_Size__c</fullName>
    <formula>Service_File__r.HOMEtracker__Household_Size__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>From Service File</inlineHelpText>
    <label>Household Size</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Outreach_Tracking__c/fields/Landlord_Developer_App_Sent__c.field-meta.xml
<CustomField>
    <fullName>Landlord_Developer_App_Sent__c</fullName>
    <inlineHelpText>Text provided by landlord / developer / seller if a their application was sent, and when. Yes or No can be answer, or a date.</inlineHelpText>
    <label>Landlord / Developer App Sent</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Outreach_Tracking__c/fields/Landlord_Developer_Deadline__c.field-meta.xml
<CustomField>
    <fullName>Landlord_Developer_Deadline__c</fullName>
    <inlineHelpText>Deadline landlord / developer has given applicant to complete their application process.</inlineHelpText>
    <label>Landlord / Developer Deadline</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Outreach_Tracking__c/fields/Landlord_Developer_Determination__c.field-meta.xml
<CustomField>
    <fullName>Landlord_Developer_Determination__c</fullName>
    <inlineHelpText>Approval or Denial provided by landlord / developer</inlineHelpText>
    <label>Landlord / Developer Determination</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Denied</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Outreach_Tracking__c/fields/Landlord_Developer_Determination_Date__c.field-meta.xml
<CustomField>
    <fullName>Landlord_Developer_Determination_Date__c</fullName>
    <inlineHelpText>Date landlord / developer determined the applicant was acceptable or not.</inlineHelpText>
    <label>Landlord / Developer Determination Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Outreach_Tracking__c/fields/Landlord_Developer_Notes__c.field-meta.xml
<CustomField>
    <fullName>Landlord_Developer_Notes__c</fullName>
    <inlineHelpText>Notes provided by landlord / developer regarding applicant.</inlineHelpText>
    <label>Landlord / Developer Notes</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Outreach_Tracking__c/fields/Landlord_Developer_Tour__c.field-meta.xml
<CustomField>
    <fullName>Landlord_Developer_Tour__c</fullName>
    <inlineHelpText>Text provided by landlord / developer if a tour occurred, and when. Yes or No can be answer, or a date.</inlineHelpText>
    <label>Landlord / Developer Tour</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Outreach_Tracking__c/fields/Move_to_Removed_Report__c.field-meta.xml
<CustomField>
    <fullName>Move_to_Removed_Report__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Check this box to move a removed applicant from the applicant tracker to the removed applicants page.</inlineHelpText>
    <label>Move to Removed Report</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Outreach_Tracking__c/fields/Outreach_Tracker_Property_Name__c.field-meta.xml
<CustomField>
    <fullName>Outreach_Tracker_Property_Name__c</fullName>
    <formula>IF( ISBLANK(Service_File__r.HOMEtracker__Property__r.Group_Property_Parent__c ),Service_File__r.HOMEtracker__Property__r.Name,Service_File__r.HOMEtracker__Property__r.Group_Property_Parent__r.Name)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Outreach Tracker Property Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Outreach_Tracking__c/fields/Priority_Calc__c.field-meta.xml
<CustomField>
    <fullName>Priority_Calc__c</fullName>
    <formula>IF( Service_File__r.Priority__c =0,1000, Service_File__r.Priority__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Priority Calc</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Outreach_Tracking__c/fields/Property_Address__c.field-meta.xml
<CustomField>
    <fullName>Property_Address__c</fullName>
    <formula>Service_File__r.HOMEtracker__Property__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Property Address</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Outreach_Tracking__c/fields/Property_Id__c.field-meta.xml
<CustomField>
    <fullName>Property_Id__c</fullName>
    <formula>IF( ISBLANK(Service_File__r.HOMEtracker__Property__r.Group_Property_Parent__c ),Service_File__r.HOMEtracker__Property__r.Id,Service_File__r.HOMEtracker__Property__r.Group_Property_Parent__r.Id)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>If part of group property, show group property ID, if not then show property ID</inlineHelpText>
    <label>Property Id Group</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Outreach_Tracking__c/fields/Property_Rent_or_List_Price__c.field-meta.xml
<CustomField>
    <fullName>Property_Rent_or_List_Price__c</fullName>
    <formula>MAX(Service_File__r.HOMEtracker__Property__r.HOMEtracker__Monthly_Rent__c,
Service_File__r.HOMEtracker__Property__r.HOMEtracker__List_Price__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Property Rent or List Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Outreach_Tracking__c/fields/Property_Unit__c.field-meta.xml
<CustomField>
    <fullName>Property_Unit__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Enter the property here, of if part of a group listing enter the appropriate property unit once applicable.</inlineHelpText>
    <label>Property / Unit</label>
    <referenceTo>HOMEtracker__Property__c</referenceTo>
    <relationshipLabel>Outreach Tracking</relationshipLabel>
    <relationshipName>Outreach_Tracking</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Outreach_Tracking__c/fields/Service_File__c.field-meta.xml
<CustomField>
    <fullName>Service_File__c</fullName>
    <label>Service File</label>
    <referenceTo>HOMEtracker__Service_File__c</referenceTo>
    <relationshipLabel>Outreach Tracking</relationshipLabel>
    <relationshipName>Outreach_Tracking</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Outreach_Tracking__c/fields/SF_Priority__c.field-meta.xml
<CustomField>
    <fullName>SF_Priority__c</fullName>
    <formula>Service_File__r.Priority__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>SF Priority</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Outreach_Tracking__c/fields/Tracker_Status__c.field-meta.xml
<CustomField>
    <fullName>Tracker_Status__c</fullName>
    <inlineHelpText>The status selected will determine if the applicants will show up on the tracker, and what color they will be highlighted.</inlineHelpText>
    <label>Tracker Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Primary</fullName>
            </value>
            <value>
                <fullName>Backup</fullName>
            </value>
            <value>
                <fullName>Flagged</fullName>
            </value>
            <value>
                <fullName>Hidden</fullName>
                <default>true</default>
                <label>Hidden</label>
            </value>
            <value>
                <fullName>Removed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Outreach_Tracking__c/fields/Unit__c.field-meta.xml
<CustomField>
    <fullName>Unit__c</fullName>
    <inlineHelpText>If applicable, enter a unit number that this applicant is in consideration for</inlineHelpText>
    <label>Unit</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/OutreachControllerLWC.cls
public with sharing class OutreachControllerLWC {
    
    // Wrapper to group OTs by property
    public class ListWrapper {
        @AuraEnabled public List<Outreach_Tracking__c> otList { get; set; }
        @AuraEnabled public Integer numOfOTs {
            get {
                return otList != null ? otList.size() : 0;
            }
            private set;
        }
        @AuraEnabled public Id firstOfList {
            get {
                return (otList != null && !otList.isEmpty()) ? otList[0].Id : null;
            }
            private set;
        }
        
        public ListWrapper(List<Outreach_Tracking__c> listOTs) {
            this.otList = listOTs;
        }
    }
    
    /**
     * Query Outreach_Tracking__c records by Property Id
     */
    @AuraEnabled(cacheable=false)
    public static Map<String, ListWrapper> getOutreachTrackingByProperty(Id propertyId) {
        if (propertyId == null) {
            return new Map<String, ListWrapper>();
        }

        List<Outreach_Tracking__c> results = [
            SELECT Id,
                   Name,
                   Property_Id__c,
                   Property_Address__c,
                   Outreach_Tracker_Property_Name__c,
                   Unit__c,
                   Property_Unit__c,
                   Property_Unit__r.Unit_Number__c,
                   Property_Unit__r.Name,
                   //Property_Unit__r.Bedrooms__c,
                   Property_Unit__r.Max_Application_Fee__c,
                   Property_Rent_or_List_Price__c,
                   SF_Priority__c,
                   Priority_Calc__c,
                   Applicant_Name__c,
                   Applicant_Email__c,
                   Applicant_Phone__c,
                   Household_Size__c,
                   Date_CGPH_Added_Name__c,
                   Date_Marked_Primary__c,
                   Date_Eligibility_Review_Began__c,
                   Date_Ready_for_Eligibility_Review__c,
                   CGPH_Determination__c,
                   CGPH_Approval_Denial_Date__c,
                   Landlord_Developer_Tour__c,
                   Landlord_Developer_Notes__c,
                   Landlord_Developer_Determination_Date__c,
                   Landlord_Developer_Determination__c,
                   Landlord_Developer_Deadline__c,
                   Landlord_Developer_App_Sent__c,
                   Tracker_Status__c,
                   Move_to_Removed_Report__c,
                   Service_File__c,
                   Service_File__r.Priority__c,
                    Service_File__r.HOMEtracker__Property__r.Id,
                    Service_File__r.HOMEtracker__Property__r.Development_address__r.Name,
                    Service_File__r.HOMEtracker__Property__r.HOMEtracker__Number_of_Bedrooms__c,
                    Service_File__r.HOMEtracker__Property__r.Max_Application_Fee__c,
                    Service_File__r.HOMEtracker__Property__r.Tracker_Order__c,
                    Service_File__r.HOMEtracker__Property__r.Income_Level__c,
                   Service_File__r.HOMEtracker__Property__r.Group_Property__c,
                   Service_File__r.HOMEtracker__Property__r.Group_Property_Parent__r.Tracker_Order__c,
                   Service_File__r.HOMEtracker__Property__r.Development_address__r.Id,
                   Service_File__r.Pre_Applicant__r.Id,
                   Service_File__r.Pre_Applicant__r.Flagged_for_Outreach__c,
                   Service_File__r.Pre_Applicant__r.Flagged_for_Outreach_Notes__c,
                   Service_File__r.Pre_Applicant__r.Last_Certification_Date__c
            FROM Outreach_Tracking__c
            WHERE Service_File__r.HOMEtracker__Property__r.Include_on_Tracker__c = true
              AND Include_On_Tracker__c = true
              AND Service_File__r.HOMEtracker__Property__r.Development_address__r.Id = :propertyId
              AND (Move_to_Removed_Report__c = false OR Move_to_Removed_Report__c = null)
            ORDER BY Priority_Calc__c ASC
        ];
        
        Map<String, ListWrapper> otByProperty = new Map<String, ListWrapper>();
        for (Outreach_Tracking__c ot : results) {
            if (ot.Property_Id__c == null) continue;
            
            if (!otByProperty.containsKey(ot.Property_Id__c)) {
                otByProperty.put(ot.Property_Id__c, new ListWrapper(new List<Outreach_Tracking__c>()));
            }
            otByProperty.get(ot.Property_Id__c).otList.add(ot);
        }
        
        return otByProperty;
    }

    /**
     * Query Outreach_Tracking__c records for a single property
     * Filters by HOMEtracker__Property__c.Id (not Development Id)
     */
    @AuraEnabled(cacheable=false)
    public static Map<String, ListWrapper> getOutreachTrackingBySingleProperty(Id propertyId) {
        if (propertyId == null) {
            return new Map<String, ListWrapper>();
        }

        List<Outreach_Tracking__c> results = [
            SELECT Id,
                   Name,
                   Property_Id__c,
                   Property_Address__c,
                   Outreach_Tracker_Property_Name__c,
                   Unit__c,
                   Property_Unit__c,
                   Property_Unit__r.Unit_Number__c,
                   Property_Unit__r.Name,
                   Property_Unit__r.Max_Application_Fee__c,
                   Property_Rent_or_List_Price__c,
                   SF_Priority__c,
                   Priority_Calc__c,
                   Applicant_Name__c,
                   Applicant_Email__c,
                   Applicant_Phone__c,
                   Household_Size__c,
                   Date_CGPH_Added_Name__c,
                   Date_Marked_Primary__c,
                   Date_Eligibility_Review_Began__c,
                   Date_Ready_for_Eligibility_Review__c,
                   CGPH_Determination__c,
                   CGPH_Approval_Denial_Date__c,
                   Landlord_Developer_Tour__c,
                   Landlord_Developer_Notes__c,
                   Landlord_Developer_Determination_Date__c,
                   Landlord_Developer_Determination__c,
                   Landlord_Developer_Deadline__c,
                   Landlord_Developer_App_Sent__c,
                   Tracker_Status__c,
                   Move_to_Removed_Report__c,
                   Service_File__c,
                   Service_File__r.Priority__c,
                    Service_File__r.HOMEtracker__Property__r.Id,
                    Service_File__r.HOMEtracker__Property__r.Development_address__r.Name,
                    Service_File__r.HOMEtracker__Property__r.HOMEtracker__Number_of_Bedrooms__c,
                    Service_File__r.HOMEtracker__Property__r.Max_Application_Fee__c,
                    Service_File__r.HOMEtracker__Property__r.Tracker_Order__c,
                    Service_File__r.HOMEtracker__Property__r.Income_Level__c,
                   Service_File__r.HOMEtracker__Property__r.Group_Property__c,
                   Service_File__r.HOMEtracker__Property__r.Group_Property_Parent__r.Tracker_Order__c,
                   Service_File__r.HOMEtracker__Property__r.Development_address__r.Id,
                   Service_File__r.Pre_Applicant__r.Id,
                   Service_File__r.Pre_Applicant__r.Flagged_for_Outreach__c,
                   Service_File__r.Pre_Applicant__r.Flagged_for_Outreach_Notes__c,
                   Service_File__r.Pre_Applicant__r.Last_Certification_Date__c
            FROM Outreach_Tracking__c
            WHERE Service_File__r.HOMEtracker__Property__r.Include_on_Tracker__c = true
              AND Include_On_Tracker__c = true
              AND (
                (Service_File__r.HOMEtracker__Property__r.Group_Property_Parent__c = null
                 AND Service_File__r.HOMEtracker__Property__r.Id = :propertyId)
                OR Service_File__r.HOMEtracker__Property__r.Group_Property_Parent__c = :propertyId
              )
              AND (Move_to_Removed_Report__c = false OR Move_to_Removed_Report__c = null)
            ORDER BY Priority_Calc__c ASC
        ];

        Map<String, ListWrapper> otByProperty = new Map<String, ListWrapper>();
        for (Outreach_Tracking__c ot : results) {
            if (ot.Property_Id__c == null) continue;

            if (!otByProperty.containsKey(ot.Property_Id__c)) {
                otByProperty.put(ot.Property_Id__c, new ListWrapper(new List<Outreach_Tracking__c>()));
            }
            otByProperty.get(ot.Property_Id__c).otList.add(ot);
        }

        return otByProperty;
    }

    /**
     * Save updates from LWC
     */
    @AuraEnabled
    public static String saveOutreachTrackings(List<Outreach_Tracking__c> updates) {
        try {
            System.debug('saveOutreachTrackings called with updates: ' + updates);
            System.debug('Updates size: ' + (updates != null ? updates.size() : 0));
            
            if (updates != null && !updates.isEmpty()) {
                for (Outreach_Tracking__c record : updates) {
                    System.debug('Record to update: ' + record);
                }
                update updates;
                System.debug('Records updated successfully');
                return 'Success';
            }
            return 'No records to update';
        } catch (Exception e) {
            System.debug('Error in saveOutreachTrackings: ' + e.getMessage());
            System.debug('Stack trace: ' + e.getStackTraceString());
            throw new AuraHandledException('Error saving records: ' + e.getMessage());
        }
    }
    
    /**
     * Alternative method to save a single record
     */
    @AuraEnabled
    public static String saveSingleOutreachTracking(String recordData) {
        try {
            System.debug('saveSingleOutreachTracking called with data: ' + recordData);
            
            Outreach_Tracking__c record = (Outreach_Tracking__c) JSON.deserialize(recordData, Outreach_Tracking__c.class);
            System.debug('Deserialized record: ' + record);
            
            update record;
            System.debug('Record updated successfully');
            return 'Success';
        } catch (Exception e) {
            System.debug('Error in saveSingleOutreachTracking: ' + e.getMessage());
            System.debug('Stack trace: ' + e.getStackTraceString());
            throw new AuraHandledException('Error saving record: ' + e.getMessage());
        }
    }
    
    /**
     * Update applicant's unit association from group property to specific unit
     * Used when internal staff assigns a specific unit to an approved applicant
     */
    @AuraEnabled
    public static String assignUnitToApplicant(Id outreachTrackingId, Id propertyUnitId) {
        try {
            System.debug('assignUnitToApplicant called with OT ID: ' + outreachTrackingId + ', Unit ID: ' + propertyUnitId);
            
            // Validate input parameters
            if (outreachTrackingId == null || propertyUnitId == null) {
                throw new AuraHandledException('Both Outreach Tracking ID and Property Unit ID are required.');
            }
            
            // Get the current record to validate it exists and is approved
            List<Outreach_Tracking__c> existingRecords = [
                SELECT Id, 
                       Property_Unit__c,
                       Landlord_Developer_Determination__c,
                       Service_File__r.HOMEtracker__Property__r.Group_Property__c
                FROM Outreach_Tracking__c 
                WHERE Id = :outreachTrackingId 
                LIMIT 1
            ];
            
            if (existingRecords.isEmpty()) {
                throw new AuraHandledException('Outreach Tracking record not found.');
            }
            
            Outreach_Tracking__c otRecord = existingRecords[0];
            
            // Validate that this is for an approved group property applicant
            if (otRecord.Service_File__r.HOMEtracker__Property__r.Group_Property__c != true) {
                throw new AuraHandledException('Unit assignment is only available for group properties.');
            }

            // Allow unit assignment for both "Approved" and "Approved Conditionally"
            if (otRecord.Landlord_Developer_Determination__c != 'Approved' &&
                otRecord.Landlord_Developer_Determination__c != 'Approved Conditionally') {
                throw new AuraHandledException('Only approved applicants can be assigned to specific units.');
            }
            
            // Update the Property_Unit__c lookup to the selected individual unit
            otRecord.Property_Unit__c = propertyUnitId;
            
            update otRecord;
            
            System.debug('Unit assignment successful - OT record updated');
            return 'Unit assigned successfully. Applicant is now associated with the specific unit.';
            
        } catch (Exception e) {
            System.debug('Error in assignUnitToApplicant: ' + e.getMessage());
            System.debug('Stack trace: ' + e.getStackTraceString());
            throw new AuraHandledException('Error assigning unit: ' + e.getMessage());
        }
    }
    
    /**
     * Cancel unit assignment and return applicant to group property association
     * Used when assignment process fails or is cancelled
     */
    @AuraEnabled
    public static String cancelUnitAssignment(Id outreachTrackingId) {
        try {
            System.debug('cancelUnitAssignment called with OT ID: ' + outreachTrackingId);
            
            if (outreachTrackingId == null) {
                throw new AuraHandledException('Outreach Tracking ID is required.');
            }
            
            // Get the current record
            List<Outreach_Tracking__c> existingRecords = [
                SELECT Id, Property_Unit__c
                FROM Outreach_Tracking__c 
                WHERE Id = :outreachTrackingId 
                LIMIT 1
            ];
            
            if (existingRecords.isEmpty()) {
                throw new AuraHandledException('Outreach Tracking record not found.');
            }
            
            Outreach_Tracking__c otRecord = existingRecords[0];
            
            // Clear the Property_Unit__c lookup to return to group property association
            otRecord.Property_Unit__c = null;
            
            update otRecord;
            
            System.debug('Unit assignment cancelled - OT record reverted to group property');
            return 'Unit assignment cancelled. Applicant returned to group property association.';
            
        } catch (Exception e) {
            System.debug('Error in cancelUnitAssignment: ' + e.getMessage());
            System.debug('Stack trace: ' + e.getStackTraceString());
            throw new AuraHandledException('Error cancelling unit assignment: ' + e.getMessage());
        }
    }
    
    /**
     * Get available units for a specific property/development
     * Used to populate unit selection options
     */
    @AuraEnabled(cacheable=true)
    public static List<HOMEtracker__Property__c> getAvailableUnitsForDevelopment(Id developmentId) {
        try {
            System.debug('getAvailableUnitsForDevelopment called with Development ID: ' + developmentId);

            if (developmentId == null) {
                return new List<HOMEtracker__Property__c>();
            }

            List<HOMEtracker__Property__c> availableUnits = [
                SELECT Id,
                       Name,
                       Unit_Number__c,
                       Development_Address__c,
                       Group_Property__c
                FROM HOMEtracker__Property__c
                WHERE Development_Address__c = :developmentId
                  AND Group_Property__c = false
                  AND Include_on_Tracker__c = true
                ORDER BY Unit_Number__c ASC
            ];

            System.debug('Found ' + availableUnits.size() + ' available units');
            return availableUnits;

        } catch (Exception e) {
            System.debug('Error in getAvailableUnitsForDevelopment: ' + e.getMessage());
            throw new AuraHandledException('Error retrieving available units: ' + e.getMessage());
        }
    }

    /**
     * Confirm removal of an applicant with "Removed" status
     * Updates Move_to_Removed_Report__c to true, which removes the applicant from the tracker
     */
    @AuraEnabled
    public static String confirmApplicantRemoval(Id outreachTrackingId) {
        try {
            System.debug('confirmApplicantRemoval called with OT ID: ' + outreachTrackingId);

            if (outreachTrackingId == null) {
                throw new AuraHandledException('Outreach Tracking ID is required.');
            }

            // Get the current record and validate it has "Removed" status
            List<Outreach_Tracking__c> existingRecords = [
                SELECT Id,
                       Tracker_Status__c,
                       Move_to_Removed_Report__c,
                       Applicant_Name__c
                FROM Outreach_Tracking__c
                WHERE Id = :outreachTrackingId
                LIMIT 1
            ];

            if (existingRecords.isEmpty()) {
                throw new AuraHandledException('Applicant record not found.');
            }

            Outreach_Tracking__c otRecord = existingRecords[0];

            // Validate that the applicant has "Removed" status
            if (otRecord.Tracker_Status__c != 'Removed') {
                throw new AuraHandledException('Only applicants with "Removed" status can be confirmed for removal.');
            }

            // Check if already moved to removal report
            if (otRecord.Move_to_Removed_Report__c == true) {
                throw new AuraHandledException('This applicant has already been moved to the removal report.');
            }

            // Update Move_to_Removed_Report__c to true
            otRecord.Move_to_Removed_Report__c = true;

            update otRecord;

            System.debug('Applicant removal confirmed - OT record updated');
            String applicantName = otRecord.Applicant_Name__c != null ? otRecord.Applicant_Name__c : 'Applicant';
            return applicantName + ' has been successfully moved to the removal report.';

        } catch (Exception e) {
            System.debug('Error in confirmApplicantRemoval: ' + e.getMessage());
            System.debug('Stack trace: ' + e.getStackTraceString());
            throw new AuraHandledException('Error confirming removal: ' + e.getMessage());
        }
    }

    /**
     * Check if a property is a group property by querying HOMEtracker__Property__c directly
     * @param propertyId - The Id of the HOMEtracker__Property__c record
     * @return Boolean - true if Group_Property__c is true, false otherwise
     */
    @AuraEnabled(cacheable=true)
    public static Boolean isGroupProperty(Id propertyId) {
        try {
            if (propertyId == null) {
                return false;
            }

            List<HOMEtracker__Property__c> properties = [
                SELECT Id, Group_Property__c
                FROM HOMEtracker__Property__c
                WHERE Id = :propertyId
                LIMIT 1
            ];

            if (properties.isEmpty()) {
                System.debug('Property not found for ID: ' + propertyId);
                return false;
            }

            Boolean isGroup = properties[0].Group_Property__c == true;
            System.debug('Property ID: ' + propertyId + ' - Is Group Property: ' + isGroup + ' - Group_Property__c value: ' + properties[0].Group_Property__c);

            return isGroup;

        } catch (Exception e) {
            System.debug('Error in isGroupProperty: ' + e.getMessage());
            System.debug('Stack trace: ' + e.getStackTraceString());
            throw new AuraHandledException('Error checking group property status: ' + e.getMessage());
        }
    }
}