force-app/main/default/objects/HOMEtracker__Property__c/HOMEtracker__Property__c.object-meta.xml
<CustomObject>
    <label>Property</label>
    <nameField>
        <label>Property Address</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Properties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/HOMEtracker__Property__c/fields/Development_address__c.field-meta.xml
<CustomField>
    <fullName>Development_address__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Development Address</label>
    <referenceTo>HOMEtracker__Property__c</referenceTo>
    <relationshipLabel>Units</relationshipLabel>
    <relationshipName>Properties</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/HOMEtracker__Property__c/fields/HOMEtracker__Status__c.field-meta.xml
<CustomField>
    <fullName>HOMEtracker__Status__c</fullName>
    <description>Please note: The data stored in this field is linked to the HomeKeeper National Data Hub. Do not change this picklist or hide this field from the layout.

Select the status that best describes this Property. Note: The Status does not automatically sync with related Contacts or Service Files.</description>
    <inlineHelpText>Select the status that best describes this Property. Note: The Status does not automatically sync with related Contacts or Service Files.</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Planned</fullName>
            </value>
            <value>
                <fullName>Under Construction</fullName>
            </value>
            <value>
                <fullName>Available for Sale/Resale - ITS Received</fullName>
            </value>
            <value>
                <fullName>Available for Sale/Resale</fullName>
            </value>
            <value>
                <fullName>Available for Sale - part of group</fullName>
                <label>Available for Sale/Resale - Part of Group</label>
            </value>
            <value>
                <fullName>Available for Sale/Resale - On Hold</fullName>
            </value>
            <value>
                <fullName>Available for Sale - in Queue</fullName>
            </value>
            <value>
                <fullName>Applications in Progress</fullName>
            </value>
            <value>
                <fullName>Sale Pending</fullName>
            </value>
            <value>
                <fullName>Sale Pending/Cert App/No PA</fullName>
            </value>
            <value>
                <fullName>Sale Pending/Cert App/PA/No Contract</fullName>
            </value>
            <value>
                <fullName>Sale Pending/In Escrow</fullName>
                <label>Sale Pending/In Escrow with Contract</label>
            </value>
            <value>
                <fullName>Owner Occupied</fullName>
            </value>
            <value>
                <fullName>Not Owner Occupied - Leased to Tenant</fullName>
            </value>
            <value>
                <fullName>Available For Rent</fullName>
                <label>Available for Rent</label>
            </value>
            <value>
                <fullName>Available for Rent - part of group</fullName>
                <label>Available for Rent - Part of Group</label>
            </value>
            <value>
                <fullName>Available for Rent - On Hold</fullName>
            </value>
            <value>
                <fullName>Available for Rent - in Queue</fullName>
            </value>
            <value>
                <fullName>Rental Pending</fullName>
            </value>
            <value>
                <fullName>Rented</fullName>
            </value>
            <value>
                <fullName>Lease Purchase Occupancy</fullName>
            </value>
            <value>
                <fullName>Estate</fullName>
            </value>
            <value>
                <fullName>Bank Owned</fullName>
            </value>
            <value>
                <fullName>Abandoned</fullName>
            </value>
            <value>
                <fullName>Initial Sales in Progress</fullName>
                <label>Initial Sales - In Progress</label>
            </value>
            <value>
                <fullName>Initial Sale of Units Completed</fullName>
                <label>Initial Sales - Completed</label>
            </value>
            <value>
                <fullName>Initial Rental/Sale On-hold bc nonresponsive</fullName>
            </value>
            <value>
                <fullName>Sold Out of Program</fullName>
            </value>
            <value>
                <fullName>Subdivided</fullName>
            </value>
            <value>
                <fullName>Initial lease up in progress</fullName>
                <label>Initial Lease Up - In Progress</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/HOMEtracker__Property__c/fields/Municipality_Name__c.field-meta.xml
<CustomField>
    <fullName>Municipality_Name__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Municipality</label>
    <referenceTo>Municipality__c</referenceTo>
    <relationshipLabel>Properties</relationshipLabel>
    <relationshipName>Properties</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/PropertyInventoryControllerTest.cls
@isTest
public class PropertyInventoryControllerTest {
    static testMethod void PropertyInventoryControllerTest(){
        
        Municipality__c objMuni = new Municipality__c();
        	objMuni.Name = 'Test Muni';
        insert objMuni;
        
        HOMEtracker__Property__c objDev = new HOMEtracker__Property__c();
        	objDev.name = 'Test Dev';
        	objDev.Municipality_Name__c = objMuni.Id;
        	objDev.HOMEtracker__Status__c = 'Initial lease up in progress';
        	objDev.RecordTypeId = '012o00000003bU2AAI';
        insert objDev;
        
        HOMEtracker__Property__c objProp1 = new HOMEtracker__Property__c();
        	objProp1.name = 'Test Dev';
        	objProp1.Municipality_Name__c = objMuni.Id;
        	objProp1.HOMEtracker__Status__c = 'Available for Rent';
        	objProp1.RecordTypeId = '012o00000003bU7AAI';
        	objProp1.Development_address__c = objDev.Id;
        insert objProp1;
        
        HOMEtracker__Property__c objProp2 = new HOMEtracker__Property__c();
        	objProp2.name = 'Test Dev';
        	objProp2.Municipality_Name__c = objMuni.Id;
        	objProp2.HOMEtracker__Status__c = 'Available for Rent';
        	objProp2.RecordTypeId = '012o00000003bU7AAI';
        	objProp1.Development_address__c = objDev.Id;
        insert objProp2;
        
        ApexPages.currentPage().getParameters().put('d', objDev.Id);
        ApexPages.currentPage().getParameters().put('g', '1');
        PropertyInventoryController controller = new PropertyInventoryController();
        controller.save();
        controller.saveT();
        
        
    }
}