force-app/main/default/objects/HOMEtracker__Property__c/HOMEtracker__Property__c.object-meta.xml
<CustomObject>
    <label>Property</label>
    <nameField>
        <label>Property Address</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Properties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/HOMEtracker__Property__c/fields/HOMEtracker__Status__c.field-meta.xml
<CustomField>
    <fullName>HOMEtracker__Status__c</fullName>
    <description>Please note: The data stored in this field is linked to the HomeKeeper National Data Hub. Do not change this picklist or hide this field from the layout.

Select the status that best describes this Property. Note: The Status does not automatically sync with related Contacts or Service Files.</description>
    <inlineHelpText>Select the status that best describes this Property. Note: The Status does not automatically sync with related Contacts or Service Files.</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Planned</fullName>
            </value>
            <value>
                <fullName>Under Construction</fullName>
            </value>
            <value>
                <fullName>Available for Sale/Resale - ITS Received</fullName>
            </value>
            <value>
                <fullName>Available for Sale/Resale</fullName>
            </value>
            <value>
                <fullName>Available for Sale - part of group</fullName>
                <label>Available for Sale/Resale - Part of Group</label>
            </value>
            <value>
                <fullName>Available for Sale/Resale - On Hold</fullName>
            </value>
            <value>
                <fullName>Available for Sale - in Queue</fullName>
            </value>
            <value>
                <fullName>Applications in Progress</fullName>
            </value>
            <value>
                <fullName>Sale Pending</fullName>
            </value>
            <value>
                <fullName>Sale Pending/Cert App/No PA</fullName>
            </value>
            <value>
                <fullName>Sale Pending/Cert App/PA/No Contract</fullName>
            </value>
            <value>
                <fullName>Sale Pending/In Escrow</fullName>
                <label>Sale Pending/In Escrow with Contract</label>
            </value>
            <value>
                <fullName>Owner Occupied</fullName>
            </value>
            <value>
                <fullName>Not Owner Occupied - Leased to Tenant</fullName>
            </value>
            <value>
                <fullName>Available For Rent</fullName>
                <label>Available for Rent</label>
            </value>
            <value>
                <fullName>Available for Rent - part of group</fullName>
                <label>Available for Rent - Part of Group</label>
            </value>
            <value>
                <fullName>Available for Rent - On Hold</fullName>
            </value>
            <value>
                <fullName>Available for Rent - in Queue</fullName>
            </value>
            <value>
                <fullName>Rental Pending</fullName>
            </value>
            <value>
                <fullName>Rented</fullName>
            </value>
            <value>
                <fullName>Lease Purchase Occupancy</fullName>
            </value>
            <value>
                <fullName>Estate</fullName>
            </value>
            <value>
                <fullName>Bank Owned</fullName>
            </value>
            <value>
                <fullName>Abandoned</fullName>
            </value>
            <value>
                <fullName>Initial Sales in Progress</fullName>
                <label>Initial Sales - In Progress</label>
            </value>
            <value>
                <fullName>Initial Sale of Units Completed</fullName>
                <label>Initial Sales - Completed</label>
            </value>
            <value>
                <fullName>Initial Rental/Sale On-hold bc nonresponsive</fullName>
            </value>
            <value>
                <fullName>Sold Out of Program</fullName>
            </value>
            <value>
                <fullName>Subdivided</fullName>
            </value>
            <value>
                <fullName>Initial lease up in progress</fullName>
                <label>Initial Lease Up - In Progress</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/HOMEtracker__Property__c/fields/Municipality_Name__c.field-meta.xml
<CustomField>
    <fullName>Municipality_Name__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Municipality</label>
    <referenceTo>Municipality__c</referenceTo>
    <relationshipLabel>Properties</relationshipLabel>
    <relationshipName>Properties</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/AALogExt_Prop_TEST.cls
@istest
public class AALogExt_Prop_TEST {
	private static testmethod void AALogExt_Prop_TEST(){
		
        Municipality__c objMuni = new Municipality__c();
		objMuni.Name = 'Test Muni';
		insert objMuni;
        
        HOMEtracker__Property__c objProp = new HOMEtracker__Property__c();
        objProp.Name = 'TEST';
        objProp.Municipality_Name__c = objMuni.Id;
        objProp.HOMEtracker__Status__c = 'Planned';
        insert objProp;

		ApexPages.currentPage().getParameters().put('id', objProp.id);
		ApexPages.StandardController std = new ApexPages.StandardController(objProp);
	    AALogExt_Prop AALogExt_Prop_TEST  = new AALogExt_Prop(std);

    }
}