force-app/main/default/objects/HOMEtracker__Property__c/HOMEtracker__Property__c.object-meta.xml
<CustomObject>
    <label>Property</label>
    <nameField>
        <label>Property Address</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Properties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/HOMEtracker__Property__c/fields/Campaign__c.field-meta.xml
<CustomField>
    <fullName>Campaign__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Campaign</label>
    <referenceTo>Campaign</referenceTo>
    <relationshipLabel>Properties</relationshipLabel>
    <relationshipName>Properties</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/HOMEtracker__Property__c/fields/Group_Property_Parent__c.field-meta.xml
<CustomField>
    <fullName>Group_Property_Parent__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>If this property is a single unit that is part of a group property for outreach, enter the group property that it is a part of in this field.</inlineHelpText>
    <label>Group Property</label>
    <referenceTo>HOMEtracker__Property__c</referenceTo>
    <relationshipLabel>Properties (Group Property)</relationshipLabel>
    <relationshipName>Group_Properties</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/HOMEtracker__Service_File__c/HOMEtracker__Service_File__c.object-meta.xml
<CustomObject>
    <description>Applications for assistance, home purchases, and other services provided</description>
    <label>Service File</label>
    <nameField>
        <label>Service File Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Services</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/HOMEtracker__Service_File__c/fields/HOMEtracker__Property__c.field-meta.xml
<CustomField>
    <fullName>HOMEtracker__Property__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup the property associated with this Service File. Tip: Create a Property record first before looking it up here. Please note: The data stored in this field is linked to the HomeKeeper National Data Hub. Do not change this field or hide it from the layout.</description>
    <inlineHelpText>Lookup the property associated with this Service File.

Tip: Create a Property record first before looking it up here.</inlineHelpText>
    <label>Property</label>
    <referenceTo>HOMEtracker__Property__c</referenceTo>
    <relationshipLabel>Services</relationshipLabel>
    <relationshipName>Property_Interests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/HOMEtracker__Service_File__c/fields/Outreach_Tracking__c.field-meta.xml
<CustomField>
    <fullName>Outreach_Tracking__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Outreach Tracking</label>
    <referenceTo>Outreach_Tracking__c</referenceTo>
    <relationshipLabel>Services</relationshipLabel>
    <relationshipName>Services</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Outreach_Tracking__c/Outreach_Tracking__c.object-meta.xml
<CustomObject>
    <description>Tracking fields for outreach</description>
    <label>Outreach Tracking</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Outreach Tracking</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Outreach_Tracking__c/fields/Service_File__c.field-meta.xml
<CustomField>
    <fullName>Service_File__c</fullName>
    <label>Service File</label>
    <referenceTo>HOMEtracker__Service_File__c</referenceTo>
    <relationshipLabel>Outreach Tracking</relationshipLabel>
    <relationshipName>Outreach_Tracking</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Outreach_Tracking__c/fields/Tracker_Status__c.field-meta.xml
<CustomField>
    <fullName>Tracker_Status__c</fullName>
    <inlineHelpText>The status selected will determine if the applicants will show up on the tracker, and what color they will be highlighted.</inlineHelpText>
    <label>Tracker Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Primary</fullName>
            </value>
            <value>
                <fullName>Backup</fullName>
            </value>
            <value>
                <fullName>Flagged</fullName>
            </value>
            <value>
                <fullName>Hidden</fullName>
                <default>true</default>
                <label>Hidden</label>
            </value>
            <value>
                <fullName>Removed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/OutreachInfoExt.cls
public class OutreachInfoExt {
    public HOMEtracker__Property__c prop {get; set;}
    public Campaign camp {get; set;}
    public List<CampaignMember> fullInvited {get; set;}
    public Integer fullInvitedCount {get; set;}
    
    public List<HOMEtracker__Property__c> groupProps {get; set;}
    public Integer groupPropsCount {get; set;}
    
    Public List<Outreach_Tracking__c> otAll {get; set;}
    Public List<Outreach_Tracking__c> otPrimary {get; set;}
    Public List<Outreach_Tracking__c> otBackup {get; set;}
    Public List<Outreach_Tracking__c> otHidden {get; set;}
    Public List<Outreach_Tracking__c> otFlagged {get; set;}
    Public List<Outreach_Tracking__c> otNone {get; set;}
    
    Public Integer otAllCount {get; set;}
    Public Integer otPrimaryCount {get; set;}
    Public Integer otBackupCount {get; set;}
    Public Integer otHiddenCount {get; set;}
    Public Integer otFlaggedCount {get; set;}
    Public Integer otNoneCount {get; set;}
    
    public OutreachInfoExt(ApexPages.StandardController controller) {
        prop = (HOMETracker__Property__c )controller.getRecord();
    
        String propId = prop.Id;
        
        prop = [SELECT Id, Name,Campaign__r.Id FROM HOMETracker__Property__c WHERE id = :propId LIMIT 1 ];
        
        String campId = prop.Campaign__r.Id;
        
        fullInvited = NULL;
        fullInvitedCount = 0;
        
        IF(prop.Campaign__c == NULL){
            campId='';
                } ELSE {
                    camp = [SELECT Id FROM Campaign WHERE id = :campId LIMIT 1];
                    
                    fullInvited = [
                                        SELECT Id
                                        FROM CampaignMember
                                        WHERE Invited_Date__c > 1900-01-01
                                                AND Campaign_Preliminary_Submission__r.Status__c = 'Invited to Submit a Full Application'
                                                AND Deadline_Date__c < TODAY
                                                AND CampaignId = :campId
                                        ORDER BY EA_Sort__c ASC
                                                ];
                                fullInvitedCount = fullInvited.size();
                }
                
        groupProps = [
            SELECT id
            FROM HOMEtracker__Property__c
            WHERE Group_Property_Parent__r.Id = :propId
                        ];
        groupPropsCount = groupProps.size();
        otAll = [
            SELECT Id, Name, Tracker_Status__c
            FROM Outreach_Tracking__c
            WHERE
                Service_File__r.HOMEtracker__Property__r.Id = :propId
                   ];

        otAllCount = otAll.size();

        otPrimary = [
            SELECT Id, Name, Tracker_Status__c
            FROM Outreach_Tracking__c
            WHERE
                Service_File__r.HOMEtracker__Property__r.Id = :propId AND
                Tracker_Status__c = 'Primary'
                   ];

        otPrimaryCount = otPrimary.size();           

        otBackup = [
            SELECT Id, Name, Tracker_Status__c
            FROM Outreach_Tracking__c
            WHERE
                Service_File__r.HOMEtracker__Property__r.Id = :propId AND
                Tracker_Status__c = 'backup'
                   ];
                   
        otBackupCount = otBackup.size();           

        otHidden = [
            SELECT Id, Name, Tracker_Status__c
            FROM Outreach_Tracking__c
            WHERE
                Service_File__r.HOMEtracker__Property__r.Id = :propId AND
                Tracker_Status__c = 'Hidden'
                   ];
                   
        otHiddenCount = otHidden.size();
                   
        otFlagged = [
            SELECT Id, Name, Tracker_Status__c
            FROM Outreach_Tracking__c
            WHERE
                Service_File__r.HOMEtracker__Property__r.Id = :propId AND
                Tracker_Status__c = 'Flagged'
                   ];
                   
        otFlaggedCount = otFlagged.size();
                   
        otNone = [
            SELECT Id, Name, Tracker_Status__c
            FROM Outreach_Tracking__c
            WHERE
                Service_File__r.HOMEtracker__Property__r.Id = :propId AND
                Tracker_Status__c = ''
                   ];
                   
         otNoneCount = otNone.size();        
                   
    }

}